"""Generate a fresh, reviewable Edron project from a migration plan."""

from __future__ import annotations

import hashlib
import json
import re
import tempfile
from pathlib import Path

from edron.migrate.report import report_payload, review_markdown
from hedron.migrate.ir import StreamlitCall, StreamlitMigrationPlan
from hedron.migrate.source_map import build_source_map, dumps_source_map


def _refuse_nonempty(path: Path) -> None:
    if path.exists() and any(path.iterdir()):
        raise FileExistsError(f"Refusing non-empty output directory: {path}")


def _name(path: Path) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]+", "-", path.name).strip("-") or "migrated-app"


def _literal(call: StreamlitCall, key: str, fallback: object) -> object:
    value = call.args_summary.get(key, fallback)
    return fallback if isinstance(value, str) and value.startswith(("<", "<name:")) else value


def _control(call: StreamlitCall) -> str | None:
    if call.symbol == "st.selectbox":
        options = _literal(call, "arg1", ["All"])
        if not isinstance(options, list) or not options:
            options = ["All"]
        options = [item for item in options if isinstance(item, (str, int, float, bool))]
        label = _literal(call, "arg0", "Select")
        name = call.assigned_to or "selection"
        return f"        self.selectbox({label!r}, {options!r}, name={name!r})"
    if call.symbol == "st.slider":
        label = _literal(call, "arg0", "Value")
        name = call.assigned_to or "value"
        minimum = _literal(call, "arg1", 0)
        maximum = _literal(call, "arg2", 100)
        default = _literal(call, "arg3", minimum)
        step = _literal(call, "step", 1)
        return (
            f"        self.slider({label!r}, name={name!r}, min_value={minimum!r}, "
            f"max_value={maximum!r}, value={default!r}, step={step!r})"
        )
    if call.symbol == "st.number_input":
        label = _literal(call, "arg0", "Value")
        name = call.assigned_to or "value"
        return f"        self.number_input({label!r}, name={name!r})"
    if call.symbol == "st.checkbox":
        label = _literal(call, "arg0", "Enabled")
        name = call.assigned_to or "enabled"
        return f"        self.checkbox({label!r}, name={name!r})"
    if call.symbol == "st.text_input":
        label = _literal(call, "arg0", "Text")
        name = call.assigned_to or "text"
        return f"        self.text_input({label!r}, name={name!r})"
    return None


def _app_source(plan: StreamlitMigrationPlan) -> str:
    title = plan.page_title or "Migrated Streamlit app"
    lines = [
        '"""Generated by ``edron migrate streamlit``. REVIEW REQUIRED."""',
        "",
        "from __future__ import annotations",
        "",
        "import os",
        "",
        "import edron as ed",
        "",
        "app = ed.App(",
        f"    title={title!r},",
        '    security="standard",',
        '    session_secret=os.environ.get("EDRON_SESSION_SECRET"),',
        ")",
        "",
        "",
        "@app.page('/', title=" + repr(title) + ")",
        "class Home(ed.Page):",
        "    def render(self) -> None:",
    ]
    body: list[str] = []
    for call in plan.calls:
        value = _literal(call, "arg0", None)
        if call.symbol == "st.title":
            body.append(
                f"        self.heading({value if isinstance(value, str) else title!r}, level=1)"
            )
        elif call.symbol in {"st.header", "st.subheader"} and isinstance(value, str):
            level = 2 if call.symbol == "st.header" else 3
            body.append(f"        self.heading({value!r}, level={level})")
        elif call.symbol in {"st.write", "st.text", "st.caption"} and isinstance(value, str):
            method = "caption" if call.symbol == "st.caption" else "text"
            body.append(f"        self.{method}({value!r})")
        elif call.symbol == "st.markdown" and isinstance(value, str):
            body.append(f"        self.markdown({value!r})")
        elif call.symbol == "st.metric" and isinstance(value, str):
            body.append(f"        self.metric({value!r}, '(review data binding)')")
        elif call.symbol in {"st.dataframe", "st.data_editor", "st.table"}:
            body.append("        # TODO: bind this table to an Edron DataWorkspace or dataframe.")
        elif call.symbol in {
            "st.line_chart",
            "st.area_chart",
            "st.bar_chart",
            "st.scatter_chart",
            "st.pyplot",
            "st.plotly_chart",
            "st.altair_chart",
        }:
            body.append("        # TODO: add an Edron chart with a textual/table alternative.")
        elif call.symbol in {
            "st.selectbox",
            "st.slider",
            "st.number_input",
            "st.checkbox",
            "st.text_input",
        }:
            control = _control(call)
            if control:
                body.append(control)
        elif call.disposition.value in {"report_only", "unsupported"}:
            body.append(
                f"        # REVIEW: {call.symbol} was not generated ({call.disposition.value})."
            )
    if not body:
        body.append("        self.text('Review migration/REVIEW.md for remaining constructs.')")
    lines.extend(body)
    lines.append("")
    return "\n".join(lines)


def _pyproject(name: str) -> str:
    return f'''[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.11,<3.15"
dependencies = [
    "edron>=0.9,<0.10",
    "hedron>=0.67.0,<0.68",
    "hedron-data>=0.67.0,<0.68",
    "uvicorn>=0.52.1",
]

[tool.edron]
component_roots = ["components"]
theme = "default"
explorer = "off"
'''


def _smoke_test() -> str:
    return """from fastapi.testclient import TestClient

from app import app


def test_home_ok() -> None:
    with TestClient(app.native) as client:
        response = client.get("/")
    assert response.status_code == 200
"""


def generate_project(plan: StreamlitMigrationPlan, out: Path) -> dict[str, str]:
    """Write a new project atomically and return generated file hashes."""
    if plan.tool_errors:
        raise RuntimeError("cannot generate while analysis tool errors are present")
    _refuse_nonempty(out)
    out = out.resolve()
    files = {
        "app.py": _app_source(plan),
        "pyproject.toml": _pyproject(_name(out)),
        "tests/test_migration_smoke.py": _smoke_test(),
    }
    files["migration/REVIEW.md"] = review_markdown(plan)
    files["migration/report.json"] = (
        json.dumps(report_payload(plan), indent=2, sort_keys=True) + "\n"
    )
    files["migration/source-map.json"] = dumps_source_map(
        build_source_map(plan, generated_files={})
    )
    hashes: dict[str, str] = {}
    out.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=out.parent) as temp:
        staging = Path(temp) / "project"
        for relative, content in files.items():
            target = staging / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            hashes[relative] = hashlib.sha256(content.encode()).hexdigest()
        source_map = dumps_source_map(build_source_map(plan, generated_files=hashes))
        report = (
            json.dumps(report_payload(plan, generated_files=hashes), indent=2, sort_keys=True)
            + "\n"
        )
        (staging / "migration/source-map.json").write_text(source_map, encoding="utf-8")
        (staging / "migration/report.json").write_text(report, encoding="utf-8")
        hashes["migration/source-map.json"] = hashlib.sha256(source_map.encode()).hexdigest()
        hashes["migration/report.json"] = hashlib.sha256(report.encode()).hexdigest()
        for item in staging.iterdir():
            destination = out / item.name
            if destination.exists():
                raise FileExistsError(f"Refusing to overwrite {destination}")
            item.rename(destination)
    (out / "components").mkdir(exist_ok=True)
    return hashes
