"""Deterministic Edron migration reports."""

from __future__ import annotations

import json
from typing import Any

from hedron.migrate.findings import plan_to_diagnostics
from hedron.migrate.ir import StreamlitMigrationPlan
from hedron_core.diagnostics import diagnostics_to_sarif, diagnostics_to_text


def report_payload(
    plan: StreamlitMigrationPlan,
    diagnostics: list[Any] | None = None,
    *,
    generated_files: dict[str, str] | None = None,
) -> dict[str, Any]:
    diagnostics = plan_to_diagnostics(plan) if diagnostics is None else diagnostics
    counts = {"error": 0, "warning": 0, "information": 0}
    for diagnostic in diagnostics:
        counts[diagnostic.severity.value] += 1
    dispositions: dict[str, int] = {}
    for call in plan.calls:
        key = call.disposition.value
        dispositions[key] = dispositions.get(key, 0) + 1
    return {
        "tool": "edron migrate streamlit",
        "target_framework": "edron",
        "generator_version": "0.7.0-beta",
        "schema_version": plan.schema_version,
        "mapping_catalog_version": plan.mapping_catalog_version,
        "streamlit_audit_baseline": plan.streamlit_audit_baseline,
        "page_title": plan.page_title,
        "extras": list(plan.extras),
        "source_units": [
            {
                "path": unit.relative_path,
                "content_hash": unit.content_hash,
                "is_entrypoint": unit.is_entrypoint,
                "is_page": unit.is_page,
            }
            for unit in plan.source_units
        ],
        "calls": plan.to_dict()["calls"],
        "findings": [diagnostic.as_json() for diagnostic in diagnostics],
        "counts": counts,
        "disposition_counts": dispositions,
        "generated_files": generated_files or {},
        "review_required": counts["error"] > 0 or counts["warning"] > 0,
        "tool_errors": list(plan.tool_errors),
    }


def format_report(
    plan: StreamlitMigrationPlan,
    diagnostics: list[Any] | None = None,
    *,
    fmt: str = "text",
    generated_files: dict[str, str] | None = None,
) -> str:
    diagnostics = plan_to_diagnostics(plan) if diagnostics is None else diagnostics
    payload = report_payload(plan, diagnostics, generated_files=generated_files)
    if fmt == "json":
        return json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if fmt == "sarif":
        return (
            json.dumps(
                diagnostics_to_sarif(diagnostics, tool_name="edron", tool_version="0.7.0-beta"),
                indent=2,
                sort_keys=True,
            )
            + "\n"
        )
    lines = [
        f"Edron Streamlit migration report ({plan.schema_version})",
        f"Catalog: {plan.mapping_catalog_version} (audit {plan.streamlit_audit_baseline})",
        f"Calls: {len(plan.calls)}  Findings: {payload['counts']}",
        f"Dispositions: {payload['disposition_counts']}",
    ]
    if payload["review_required"]:
        lines.append("REVIEW REQUIRED")
    if plan.tool_errors:
        lines.extend(["Tool errors:", *(f"  - {error}" for error in plan.tool_errors)])
    lines.append("")
    lines.append(diagnostics_to_text(diagnostics) if diagnostics else "No findings.")
    return "\n".join(lines) + "\n"


def review_markdown(plan: StreamlitMigrationPlan, diagnostics: list[Any] | None = None) -> str:
    diagnostics = plan_to_diagnostics(plan) if diagnostics is None else diagnostics
    lines = [
        "# Edron migration review",
        "",
        "Generated by `edron migrate streamlit`. This is a reviewable Edron project,",
        "not a claim of behavioral equivalence. The source was not modified.",
        "",
        f"- Schema: `{plan.schema_version}`",
        f"- Mapping catalog: `{plan.mapping_catalog_version}`",
        f"- Streamlit audit baseline: `{plan.streamlit_audit_baseline}`",
        f"- Page title: {plan.page_title or '(none detected)'}",
        "",
        "## Findings",
        "",
    ]
    if diagnostics:
        lines.extend(f"- `{d.code}` ({d.severity.value}) {d.explanation}" for d in diagnostics)
    else:
        lines.append("_None._")
    lines.extend(
        [
            "",
            "## Next steps",
            "",
            "1. Assign ownership for state, side effects, dependencies, security, and",
            "   accessibility.",
            "2. Move mutations to explicit Edron actions with CSRF and authorization.",
            "3. Run the smoke test and replace every TODO before production deployment.",
            "",
        ]
    )
    return "\n".join(lines)
