"""Portable testing helpers for hedron-core."""

from hedron_core.testing.adapters import (
    AdapterAppFixture,
    AdapterResponse,
    assert_fragment_body,
    assert_html_contains,
    assert_htmx_trigger,
    assert_hx_push_url,
    assert_hx_redirect,
    assert_hx_reswap,
    assert_hx_retarget,
    assert_oob_present,
    assert_page_document,
    assert_toast_markup,
    django_fixture,
    fastapi_fixture,
    flask_fixture,
)
from hedron_core.testing.app import (
    AppScenario,
    MarkedElement,
    find_all_marks,
    find_mark,
)
from hedron_core.testing.async_scenario import (
    AsyncScenario,
    ControllableClock,
    ScriptedDependency,
    assert_ordered_events,
    scripted_outcome,
)
from hedron_core.testing.fixtures import (
    AuthPrincipal,
    BrowserHintFixture,
    NamedConnectionFixture,
    OidcCallbackStub,
    StoragePayload,
    UploadFixture,
    redact_secrets_for_failure,
    validate_fixture,
)
from hedron_core.testing.htmx_asserts import (
    assert_shell_dual_path,
    assert_ui_targets_subset_of_regions,
    assert_undeclared_target_rejected,
)
from hedron_core.testing.workbench import (
    SandboxBudgetFixture,
    assert_action_authorized,
    assert_http_fallback_present,
    assert_transform_plan_bounded,
    image_region_fixture,
    json_document_fixture,
    sandbox_budget_fixture,
    tree_document_fixture,
    workbench_action_fixture,
)

__all__ = [
    "AdapterAppFixture",
    "AdapterResponse",
    "AppScenario",
    "AsyncScenario",
    "AuthPrincipal",
    "BrowserHintFixture",
    "ControllableClock",
    "MarkedElement",
    "NamedConnectionFixture",
    "OidcCallbackStub",
    "SandboxBudgetFixture",
    "ScriptedDependency",
    "StoragePayload",
    "UploadFixture",
    "assert_action_authorized",
    "assert_fragment_body",
    "assert_html_contains",
    "assert_http_fallback_present",
    "assert_htmx_trigger",
    "assert_hx_push_url",
    "assert_hx_redirect",
    "assert_hx_reswap",
    "assert_hx_retarget",
    "assert_oob_present",
    "assert_ordered_events",
    "assert_page_document",
    "assert_shell_dual_path",
    "assert_toast_markup",
    "assert_transform_plan_bounded",
    "assert_ui_targets_subset_of_regions",
    "assert_undeclared_target_rejected",
    "django_fixture",
    "fastapi_fixture",
    "find_all_marks",
    "find_mark",
    "flask_fixture",
    "image_region_fixture",
    "json_document_fixture",
    "redact_secrets_for_failure",
    "sandbox_budget_fixture",
    "scripted_outcome",
    "tree_document_fixture",
    "validate_fixture",
    "workbench_action_fixture",
]
