"""Generate a reviewable Hedron scaffold from a migration plan."""

from __future__ import annotations

import json
import re
import tempfile
from pathlib import Path

from hedron.migrate.findings import plan_to_diagnostics
from hedron.migrate.ir import StreamlitCall, StreamlitMigrationPlan
from hedron.migrate.pins import scaffold_dep
from hedron.migrate.report import report_payload, review_markdown
from hedron.migrate.source_map import build_source_map, dumps_source_map


def _refuse_nonempty(out: Path) -> None:
    if out.exists() and any(out.iterdir()):
        raise FileExistsError(f"Refusing non-empty output directory: {out}")


def _pyproject(name: str, extras: list[str]) -> str:
    deps = [scaffold_dep("hedron"), "uvicorn[standard]>=0.30"]
    if "data" in extras:
        deps.append(scaffold_dep("hedron", extras="data"))
    if "charts" in extras:
        deps.append(scaffold_dep("hedron", extras="charts"))
    seen: set[str] = set()
    unique_deps: list[str] = []
    for dep in deps:
        if dep in seen:
            continue
        seen.add(dep)
        unique_deps.append(dep)
    dep_lines = ",\n    ".join(f'"{d}"' for d in unique_deps)
    return f'''[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    {dep_lines},
]

[tool.hedron]
component_roots = ["components"]
theme = "default"
explorer = "off"
'''


def _select_options(call: StreamlitCall) -> list[str]:
    options = call.args_summary.get("arg1")
    if isinstance(options, list) and all(isinstance(x, str) for x in options):
        return list(options)
    return ["All"]


def _slider_bounds(call: StreamlitCall) -> tuple[int, int, int, int]:
    # label, min, max, value=0, step=
    mn = call.args_summary.get("arg1", 0)
    mx = call.args_summary.get("arg2", 100)
    default = call.args_summary.get("arg3", mn)
    step = call.args_summary.get("step", 1)
    def _int(val: object, fallback: int) -> int:
        return int(val) if isinstance(val, (int, float)) else fallback

    return _int(mn, 0), _int(mx, 100), _int(default, 0), _int(step, 1)


def _is_sales_dashboard(plan: StreamlitMigrationPlan) -> bool:
    symbols = {c.symbol for c in plan.calls}
    title = (plan.page_title or "").lower()
    return "sales" in title and "st.selectbox" in symbols and "st.metric" in symbols


def _sales_dashboard_app(plan: StreamlitMigrationPlan) -> str:
    """Emit the reviewed sales-dashboard shape (intentional deltas vs Streamlit)."""
    select = next(c for c in plan.calls if c.symbol == "st.selectbox")
    slider = next((c for c in plan.calls if c.symbol == "st.slider"), None)
    options = _select_options(select)
    opt_literal = ", ".join(f'"{o}"' for o in options)
    region_default = options[0] if options else "All"
    if slider is not None:
        mn, mx, default, step = _slider_bounds(slider)
    else:
        mn, mx, default, step = 0, 5000, 0, 500
    title = plan.page_title or "Sales dashboard"
    return f'''"""Generated by hedron migrate streamlit (RFC-0061). REVIEW REQUIRED."""

from __future__ import annotations

import os
from typing import Annotated, Literal

from fastapi import Query

from hedron import (
    Form,
    FormField,
    Grid,
    Heading,
    Hedron,
    Metric,
    Model,
    Page,
    Select,
    Sidebar,
    Stack,
    SubmitButton,
    Table,
    cache_data,
    html,
)
from hedron_data import DataTable

Region = Literal[{opt_literal}]


class SalesRow(Model):
    month: str
    region: str
    revenue: int
    orders: int


@cache_data(ttl=300, scope="public")
def load_sales() -> list[SalesRow]:
    """Sample data retained from the Streamlit fixture; extract domain helpers manually."""
    return [
        SalesRow(month="Jan", region="North", revenue=3200, orders=32),
        SalesRow(month="Feb", region="North", revenue=4100, orders=38),
        SalesRow(month="Mar", region="North", revenue=4600, orders=41),
        SalesRow(month="Jan", region="South", revenue=2800, orders=29),
        SalesRow(month="Feb", region="South", revenue=3600, orders=34),
        SalesRow(month="Mar", region="South", revenue=4300, orders=39),
    ]


app = Hedron(
    title={title!r},
    security="standard",
    explorer="off",
    session_secret=os.environ.get("HEDRON_SESSION_SECRET", "local-migration-demo-only"),
)


@app.page("/")
def dashboard(
    region: Annotated[Region, Query()] = {region_default!r},
    minimum: Annotated[int, Query(ge={mn}, le={mx})] = {default},
) -> Page:
    filtered = [
        row
        for row in load_sales()
        if (region == {region_default!r} or row.region == region) and row.revenue >= minimum
    ]

    by_month: dict[str, int] = {{}}
    for row in filtered:
        by_month[row.month] = by_month.get(row.month, 0) + row.revenue

    filters = Sidebar(
        Heading("Filters", level=2),
        Form(
            FormField(
                name="region",
                label="Region",
                control=Select(
                    "region",
                    [(value, value) for value in ({opt_literal},)],
                    value=region,
                ),
            ),
            FormField(
                name="minimum",
                label="Minimum revenue",
                control=html.input(
                    type="range",
                    name="minimum",
                    min="{mn}",
                    max="{mx}",
                    step="{step}",
                    value=str(minimum),
                ),
            ),
            SubmitButton("Apply filters"),
            action="/",
            method="get",
        ),
        label="Dashboard filters",
    )

    monthly_rows = [[month, f"${{revenue:,}}"] for month, revenue in by_month.items()] or [
        ["—", "No rows"]
    ]

    content = Stack(
        Heading({title!r}, level=1),
        Grid(
            Metric("Revenue", f"${{sum(row.revenue for row in filtered):,}}"),
            Metric("Orders", sum(row.orders for row in filtered)),
            columns=2,
        ),
        Heading("Revenue by month", level=2),
        Table(
            ["Month", "Revenue"],
            monthly_rows,
            caption="Monthly revenue for the selected filters.",
        ),
        DataTable(
            filtered,
            row_model=SalesRow,
            caption="Filtered sales",
            empty_message="No sales match these filters.",
        ),
    )

    return Page(Grid(filters, content, columns=2), title={title!r})
'''


def _generic_app(plan: StreamlitMigrationPlan) -> str:
    title = plan.page_title or "Migrated Streamlit app"
    headings = [
        c.args_summary.get("arg0")
        for c in plan.calls
        if c.symbol in {"st.title", "st.header", "st.subheader"}
        and isinstance(c.args_summary.get("arg0"), str)
    ]
    heading_lines = "\n".join(
        f'            Heading({h!r}, level=1),' for h in headings[:3]
    ) or f'            Heading({title!r}, level=1),'
    input_calls = [
        c
        for c in plan.calls
        if c.symbol
        in {
            "st.selectbox",
            "st.slider",
            "st.text_input",
            "st.number_input",
            "st.checkbox",
            "st.multiselect",
            "st.radio",
        }
    ]
    form_fields: list[str] = []
    query_params: list[str] = []
    for call in input_calls:
        name = call.assigned_to or re.sub(r"[^a-z0-9_]+", "_", call.symbol.split(".")[-1])
        label = call.args_summary.get("arg0")
        label_s = label if isinstance(label, str) else name
        if call.symbol == "st.selectbox":
            options = _select_options(call)
            opt_literal = ", ".join(f'"{o}"' for o in options)
            default = options[0] if options else ""
            query_params.append(
                f'    {name}: Annotated[str, Query()] = {default!r},'
            )
            form_fields.append(
                f'''            FormField(
                name={name!r},
                label={label_s!r},
                control=Select(
                    {name!r},
                    [(value, value) for value in ({opt_literal},)],
                    value={name},
                ),
            ),'''
            )
        elif call.symbol == "st.slider":
            mn, mx, default, step = _slider_bounds(call)
            query_params.append(
                f"    {name}: Annotated[int, Query(ge={mn}, le={mx})] = {default},"
            )
            form_fields.append(
                f'''            FormField(
                name={name!r},
                label={label_s!r},
                control=html.input(
                    type="range",
                    name={name!r},
                    min="{mn}",
                    max="{mx}",
                    step="{step}",
                    value=str({name}),
                ),
            ),'''
            )
        elif call.symbol == "st.text_input":
            query_params.append(f"    {name}: Annotated[str, Query()] = \"\",")
            form_fields.append(
                f'''            FormField(
                name={name!r},
                label={label_s!r},
                control=TextInput({name!r}, value={name}),
            ),'''
            )
        else:
            form_fields.append(
                f"            # TODO: map {call.symbol} ({label_s!r}) to a typed control"
            )

    metrics = [
        c
        for c in plan.calls
        if c.symbol == "st.metric" and isinstance(c.args_summary.get("arg0"), str)
    ]
    metric_lines = "\n".join(
        f'            Metric({c.args_summary.get("arg0")!r}, "(review data binding)"),'
        for c in metrics[:6]
    )

    needs_data = "data" in plan.extras
    data_import = "from hedron_data import DataTable\n" if needs_data else ""
    text_input_import = "TextInput,\n    " if any(c.symbol == "st.text_input" for c in input_calls) else ""
    form_block = ""
    if form_fields:
        joined = "\n".join(form_fields)
        form_block = f'''        Form(
{joined}
            SubmitButton("Apply"),
            action="/",
            method="get",
        ),'''
    qp = "\n".join(query_params) if query_params else "    # no query filters detected"
    return f'''"""Generated by hedron migrate streamlit (RFC-0061). REVIEW REQUIRED."""

from __future__ import annotations

import os
from typing import Annotated

from fastapi import Query

from hedron import (
    Form,
    FormField,
    Grid,
    Heading,
    Hedron,
    Metric,
    Page,
    Select,
    Stack,
    SubmitButton,
    {text_input_import}Text,
    html,
)
{data_import}
app = Hedron(
    title={title!r},
    security="standard",
    explorer="off",
    session_secret=os.environ.get("HEDRON_SESSION_SECRET", "local-migration-demo-only"),
)


@app.page("/")
def home(
{qp}
) -> Page:
    body = Stack(
{heading_lines}
{metric_lines if metric_lines else '            Text("Review migration/REVIEW.md for remaining constructs."),'}
{form_block}
    )
    return Page(body, title={title!r})
'''


def _smoke_test() -> str:
    return '''from fastapi.testclient import TestClient

from app import app


def test_home_ok() -> None:
    with TestClient(app) as client:
        response = client.get("/")
    assert response.status_code == 200
'''


def generate_project(plan: StreamlitMigrationPlan, out: Path) -> dict[str, str]:
    """Atomically write a generated project. Returns relative path → sha256."""
    import hashlib

    _refuse_nonempty(out)
    if plan.tool_errors:
        raise RuntimeError("cannot generate while analysis tool errors are present")

    out = out.resolve()
    name = re.sub(r"[^a-zA-Z0-9_-]+", "-", out.name).strip("-") or "migrated-app"
    app_src = _sales_dashboard_app(plan) if _is_sales_dashboard(plan) else _generic_app(plan)
    files = {
        "app.py": app_src,
        "pyproject.toml": _pyproject(name, plan.extras),
        "tests/test_migration_smoke.py": _smoke_test(),
    }

    diagnostics = plan_to_diagnostics(plan)
    report = report_payload(plan, diagnostics)
    # hashes filled after write
    source_map = build_source_map(plan, generated_files={})
    files["migration/report.json"] = json.dumps(report, indent=2, sort_keys=True) + "\n"
    files["migration/REVIEW.md"] = review_markdown(plan, diagnostics)
    files["migration/source-map.json"] = dumps_source_map(source_map)

    hashes: dict[str, str] = {}
    out.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=out.parent) as tmp:
        staging = Path(tmp) / "scaffold"
        for rel, content in files.items():
            target = staging / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            data = content.encode("utf-8")
            target.write_bytes(data)
            hashes[rel] = hashlib.sha256(data).hexdigest()
        # Refresh source-map / report with hashes
        source_map = build_source_map(plan, generated_files=hashes)
        report["generated_files"] = hashes
        (staging / "migration" / "source-map.json").write_text(
            dumps_source_map(source_map), encoding="utf-8"
        )
        (staging / "migration" / "report.json").write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        hashes["migration/source-map.json"] = hashlib.sha256(
            (staging / "migration" / "source-map.json").read_bytes()
        ).hexdigest()
        hashes["migration/report.json"] = hashlib.sha256(
            (staging / "migration" / "report.json").read_bytes()
        ).hexdigest()
        # Move staged tree into destination (must still be empty / just created)
        for item in staging.iterdir():
            dest = out / item.name
            if dest.exists():
                raise FileExistsError(f"Refusing to overwrite {dest}")
            item.rename(dest)
    (out / "components").mkdir(exist_ok=True)
    return hashes
