"""Migration report formatting (text / JSON / SARIF) and REVIEW.md."""

from __future__ import annotations

import json
from typing import Any

from hedron.migrate.ir import StreamlitMigrationPlan
from hedron_core.diagnostics import (
    Diagnostic,
    DiagnosticSeverity,
    diagnostics_to_sarif,
    diagnostics_to_text,
)


def report_payload(
    plan: StreamlitMigrationPlan,
    diagnostics: list[Diagnostic],
    *,
    generated_files: dict[str, str] | None = None,
) -> dict[str, Any]:
    counts = {
        "error": 0,
        "warning": 0,
        "information": 0,
    }
    for diag in diagnostics:
        counts[diag.severity.value] += 1
    disposition_counts: dict[str, int] = {}
    for call in plan.calls:
        disposition_counts[call.disposition.value] = (
            disposition_counts.get(call.disposition.value, 0) + 1
        )
    return {
        "schema_version": plan.schema_version,
        "mapping_catalog_version": plan.mapping_catalog_version,
        "streamlit_audit_baseline": plan.streamlit_audit_baseline,
        "page_title": plan.page_title,
        "extras": list(plan.extras),
        "source_units": [
            {
                "path": u.relative_path,
                "content_hash": u.content_hash,
                "is_entrypoint": u.is_entrypoint,
                "is_page": u.is_page,
            }
            for u in plan.source_units
        ],
        "calls": plan.to_dict()["calls"],
        "findings": [d.as_json() for d in diagnostics],
        "counts": counts,
        "disposition_counts": disposition_counts,
        "generated_files": generated_files or {},
        "review_required": counts["error"] > 0 or counts["warning"] > 0,
        "tool_errors": list(plan.tool_errors),
    }


def format_report(
    plan: StreamlitMigrationPlan,
    diagnostics: list[Diagnostic],
    *,
    fmt: str,
    generated_files: dict[str, str] | None = None,
) -> str:
    payload = report_payload(plan, diagnostics, generated_files=generated_files)
    if fmt == "json":
        return json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if fmt == "sarif":
        return json.dumps(diagnostics_to_sarif(diagnostics), indent=2, sort_keys=True) + "\n"
    # text
    lines = [
        f"Hedron Streamlit migration report ({plan.schema_version})",
        f"Catalog: {plan.mapping_catalog_version} (audit {plan.streamlit_audit_baseline})",
        f"Calls: {len(plan.calls)}  Findings: {payload['counts']}",
        f"Dispositions: {payload['disposition_counts']}",
    ]
    if payload["review_required"]:
        lines.append("REVIEW REQUIRED")
    if plan.tool_errors:
        lines.append("Tool errors:")
        lines.extend(f"  - {err}" for err in plan.tool_errors)
    lines.append("")
    if diagnostics:
        lines.append(diagnostics_to_text(diagnostics))
    else:
        lines.append("No findings.")
    return "\n".join(lines) + "\n"


def review_markdown(plan: StreamlitMigrationPlan, diagnostics: list[Diagnostic]) -> str:
    lines = [
        "# Migration review",
        "",
        "Generated by `hedron migrate streamlit` (RFC-0061). This scaffold is a candidate,",
        "not a claim of behavioral equivalence. Source files were not modified.",
        "",
        f"- Schema: `{plan.schema_version}`",
        f"- Mapping catalog: `{plan.mapping_catalog_version}`",
        f"- Streamlit audit baseline: `{plan.streamlit_audit_baseline}`",
        f"- Page title: {plan.page_title or '(none detected)'}",
        "",
        "## Findings by severity",
        "",
    ]
    by_sev: dict[str, list[Diagnostic]] = {
        DiagnosticSeverity.ERROR.value: [],
        DiagnosticSeverity.WARNING.value: [],
        DiagnosticSeverity.INFORMATION.value: [],
    }
    for diag in diagnostics:
        by_sev[diag.severity.value].append(diag)
    for sev in ("error", "warning", "information"):
        items = by_sev[sev]
        lines.append(f"### {sev} ({len(items)})")
        lines.append("")
        if not items:
            lines.append("_None._")
            lines.append("")
            continue
        for diag in items:
            loc = ""
            if diag.span is not None:
                loc = f" (`{diag.span.path}:{diag.span.start_line}`)"
            lines.append(f"- `{diag.code}` {diag.title}{loc}: {diag.explanation}")
        lines.append("")
    lines.extend(
        [
            "## Next steps",
            "",
            "1. Review ownership for every former widget and `st.session_state` key.",
            "2. Move mutations to CSRF-protected POST actions.",
            "3. Run the generated smoke test, then follow",
            "   [streamlit-cutover.md](https://hedron.readthedocs.io/en/latest/guides/streamlit-cutover/).",
            "",
        ]
    )
    return "\n".join(lines)
