"""hedron: FastAPI-native typed component framework."""

from __future__ import annotations

from typing import TYPE_CHECKING

from hedron.app import Hedron, mount_hedron_static
from hedron.builtins import (
    AutoForm,
    ErrorState,
    InfiniteScroll,
    Lazy,
    Loading,
    Pagination,
    Poll,
    RefreshButton,
    action_attrs,
    oob_swap,
)
from hedron.builtins.files import DownloadButton, FileUpload, safe_download_response
from hedron.cache import cache_component, cache_data
from hedron.color_mode import (
    apply_color_mode_cookie,
    read_color_mode_preference,
    resolved_theme_from_request,
)
from hedron.htmx import approved_headers, htmx_context
from hedron.responses import (
    HTML,
    ComponentResponse,
    FileComponentResponse,
    FragmentResponse,
    PageResponse,
    hedron_response,
    merge_htmx_headers,
)
from hedron.routing import ComponentRef, HedronRoute, HedronRouter, resolve_route_path
from hedron.security import (
    SecurityPolicy,
    SecurityProfile,
    redirect_external,
    redirect_local,
)
from hedron.state import SessionState, session_state

# Re-export beginner core API.
from hedron_core import (  # noqa: F401
    Alert,
    Aside,
    Auto,
    Badge,
    Button,
    Card,
    Checkbox,
    CodeBlock,
    CodeViewer,
    ColorMode,
    ColorModeToggle,
    Component,
    Container,
    DescriptionList,
    Divider,
    Expander,
    Field,
    Footer,
    Form,
    FormErrors,
    FormField,
    FormModel,
    Fragment,
    Grid,
    Head,
    Header,
    Heading,
    IconButton,
    Image,
    Inline,
    JSONViewer,
    Label,
    Link,
    LinkButton,
    List,
    Main,
    Metric,
    Model,
    Nav,
    Page,
    Progress,
    Props,
    RadioGroup,
    RenderContext,
    RenderMode,
    RenderResult,
    SafeUrl,
    Secret,
    Section,
    Select,
    Sidebar,
    Skeleton,
    Stack,
    Status,
    StyleSymbols,
    SubmitButton,
    Table,
    Tabs,
    Text,
    TextArea,
    TextInput,
    Theme,
    Title,
    Toast,
    TrustedHtml,
    UrlPurpose,
    addressable,
    compile_css,
    compile_hdn,
    format_hdn,
    html,
    invalidate_tags,
    render,
    resolve_color_mode,
    run_program,
    styles_from_manifest,
)

if TYPE_CHECKING:
    from hedron_data import (
        DataChanges,
        DataEditor,
        DataPage,
        DataQuery,
        DataSaveResult,
        DataTable,
        InMemoryDataSource,
    )

_DATA_EXPORTS = frozenset(
    {
        "DataChanges",
        "DataEditor",
        "DataPage",
        "DataQuery",
        "DataSaveResult",
        "DataTable",
        "InMemoryDataSource",
    }
)


def __getattr__(name: str) -> object:
    if name in _DATA_EXPORTS:
        try:
            import hedron_data as _hedron_data
        except ImportError as exc:  # pragma: no cover - exercised when extra missing
            raise ImportError(
                f"{name} requires the hedron-data package. "
                'Install with: pip install "hedron[data]" or pip install hedron-data'
            ) from exc
        return getattr(_hedron_data, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__version__ = "0.5.0"

__all__ = [
    "Alert",
    "Aside",
    "AutoForm",
    "Badge",
    "Button",
    "Card",
    "Checkbox",
    "CodeBlock",
    "Component",
    "ComponentRef",
    "ComponentResponse",
    "Container",
    "DescriptionList",
    "Divider",
    "ErrorState",
    "Field",
    "FileComponentResponse",
    "Footer",
    "Form",
    "FormErrors",
    "FormField",
    "FormModel",
    "Fragment",
    "FragmentResponse",
    "Grid",
    "HTML",
    "Head",
    "Header",
    "Heading",
    "Hedron",
    "HedronRoute",
    "HedronRouter",
    "IconButton",
    "Image",
    "InfiniteScroll",
    "Inline",
    "Label",
    "Lazy",
    "Link",
    "LinkButton",
    "List",
    "Loading",
    "Main",
    "Model",
    "Nav",
    "Page",
    "PageResponse",
    "Pagination",
    "Poll",
    "Props",
    "RadioGroup",
    "RefreshButton",
    "RenderContext",
    "RenderMode",
    "RenderResult",
    "SafeUrl",
    "Secret",
    "Section",
    "SecurityPolicy",
    "SecurityProfile",
    "Select",
    "SessionState",
    "Skeleton",
    "Stack",
    "StyleSymbols",
    "SubmitButton",
    "Table",
    "Text",
    "TextArea",
    "TextInput",
    "Theme",
    "Title",
    "TrustedHtml",
    "UrlPurpose",
    "Auto",
    "CodeViewer",
    "ColorMode",
    "ColorModeToggle",
    "DataChanges",
    "DataEditor",
    "DataPage",
    "DataQuery",
    "DataSaveResult",
    "DataTable",
    "DownloadButton",
    "Expander",
    "FileUpload",
    "InMemoryDataSource",
    "JSONViewer",
    "Metric",
    "Progress",
    "Sidebar",
    "Status",
    "Tabs",
    "Toast",
    "apply_color_mode_cookie",
    "cache_component",
    "cache_data",
    "invalidate_tags",
    "read_color_mode_preference",
    "resolve_color_mode",
    "resolved_theme_from_request",
    "safe_download_response",
    "__version__",
    "action_attrs",
    "addressable",
    "approved_headers",
    "compile_css",
    "compile_hdn",
    "format_hdn",
    "hedron_response",
    "html",
    "htmx_context",
    "merge_htmx_headers",
    "mount_hedron_static",
    "oob_swap",
    "redirect_external",
    "redirect_local",
    "render",
    "resolve_route_path",
    "run_program",
    "session_state",
    "styles_from_manifest",
]
