"""hedron: FastAPI-native typed component framework."""

from __future__ import annotations

from typing import TYPE_CHECKING

from hedron.app import Hedron, mount_hedron_static
from hedron.app.screens import ScreenHandle, ScreenLayout
from hedron.async_utils import await_if_needed, gather, run_sync
from hedron.auth import (
    AuthDenied,
    AuthResult,
    AuthSuccess,
    RateLimitPolicy,
    SessionAuthFlow,
    SessionRotationPolicy,
)
from hedron.browser import browser_context, browser_context_from_request
from hedron.builtins import (
    AutoForm,
    ErrorState,
    InfiniteScroll,
    Lazy,
    Loading,
    LoginCsrfField,
    Pagination,
    Poll,
    RefreshButton,
    action_attrs,
    oob_swap,
)
from hedron.builtins.chat import ChatInput
from hedron.builtins.files import DownloadButton, FileUpload, safe_download_response
from hedron.builtins.media import (
    ByteRangeNotSatisfiable,
    download_all_zip,
    media_file_response,
    parse_byte_range,
)
from hedron.cache import cache_component, cache_data
from hedron.color_mode import (
    apply_color_mode_cookie,
    read_color_mode_preference,
    resolved_theme_from_request,
)
from hedron.dashboard import CachePolicy, DashboardHistory, DashboardWorkspace
from hedron.files import UploadFlow
from hedron.handles import (
    ActionHandle,
    BoundFragment,
    FragmentHandle,
    Refresh,
    patches,
    refresh,
)
from hedron.htmx import approved_headers, htmx_context
from hedron.interaction import (
    FragmentRegion,
    FragmentRegionError,
    HtmxRequest,
    InteractionPolicy,
    InteractionResult,
    OobUpdate,
    default_interaction_policy,
    form_sync_attrs,
    htmx_request,
    redirect_htmx,
    retarget,
    swap,
    swap_oob,
)
from hedron.jobs import (
    JobScope,
    JobScopeProvider,
    PollPolicy,
    TaskFlow,
    TaskUnavailablePolicy,
)
from hedron.mount import (
    MountPath,
    cookie_path_for_mount,
    mount_from_request,
    normalize_mount_path,
    prefix_local_path,
    resolve_mount_path,
    resolve_mount_path_from_environ,
)
from hedron.recorder import (
    InteractionRecorder,
    RecordedExchange,
    RecordingSnippet,
)
from hedron.responses import (
    HTML,
    ComponentResponse,
    FileComponentResponse,
    FragmentResponse,
    PageResponse,
    hedron_response,
    merge_htmx_headers,
    render_component_response,
    render_interaction,
)
from hedron.routing import ComponentRef, HedronRoute, HedronRouter, resolve_route_path
from hedron.security import (
    SecurityHeadersPolicy,
    SecurityPolicy,
    SecurityProfile,
    csrf_token_for_request,
    redirect_external,
    redirect_local,
)
from hedron.state import SessionState, session_state
from hedron.type_authoring import (
    CommandHandler,
    CommandResult,
    Control,
    FormBody,
    OutcomeMap,
    RefreshableView,
    Refreshes,
    Updates,
    ViewParams,
    case,
)
from hedron.type_authoring.depends import DependsOn

# Re-export beginner core API.
from hedron_core import (
    AccountSummary,
    ActionDock,
    ActionGroup,
    ActionRegistry,
    Alert,
    AppFooter,
    AppShell,
    Aside,
    AttrHost,
    Audio,
    Auto,
    Avatar,
    Badge,
    BottomDock,
    Brand,
    BrowserContext,
    BrowserStorage,
    BrowserStorageUnavailable,
    Button,
    CameraCapture,
    Card,
    Carousel,
    CatalogEntry,
    CatalogVersionError,
    ChatMessage,
    Checkbox,
    ChipInput,
    CircularProgress,
    ClipboardCopy,
    CodeBlock,
    CodeViewer,
    ColorInput,
    ColorMode,
    ColorModeToggle,
    Component,
    ConfirmButton,
    Container,
    ContextMenu,
    CsrfField,
    CsrfStrategy,
    CsrfValidationError,
    DateInput,
    DateTimeInput,
    DescriptionList,
    DesignSystem,
    Dialog,
    Dialogue,
    DialogueTurn,
    DirectoryUpload,
    Divider,
    DoubleSubmitCookieCsrf,
    EnvironmentBanner,
    ExampleItem,
    ExampleSet,
    Expander,
    FeedbackPolicy,
    Field,
    FlowStep,
    Footer,
    Form,
    FormErrors,
    FormField,
    FormGrid,
    FormModel,
    Fragment,
    FragmentHost,
    Gallery,
    GeoJSONLayer,
    GeolocationButton,
    GeolocationHint,
    Grid,
    GridItem,
    Head,
    Header,
    Heading,
    Help,
    HelpInspector,
    HtmxLink,
    Hx,
    Icon,
    IconButton,
    Identity,
    IFrame,
    Image,
    InferenceInterface,
    InferencePolicy,
    InferenceWorkflow,
    Inline,
    InstanceKey,
    InteractionCatalog,
    InteractionManifest,
    JSONViewer,
    Label,
    Link,
    LinkButton,
    List,
    Logo,
    Main,
    MainPanel,
    Map,
    MasterDetail,
    Math,
    MenuButton,
    Metric,
    MicrophoneCapture,
    Model,
    ModelDemo,
    MultiSelect,
    Nav,
    NavLink,
    NavStatus,
    NumberInput,
    OobHost,
    PackageProjection,
    Page,
    PageHeader,
    PageIcon,
    ParameterViewer,
    Patch,
    PatchSet,
    PdfViewer,
    Pills,
    Popover,
    PredictionFeedback,
    PredictionLabel,
    PredictionScore,
    ProcessFlow,
    Progress,
    ProjectionCapability,
    Props,
    RadioGroup,
    RangeInput,
    RatingInput,
    RefreshIntent,
    RegisteredAction,
    RenderContext,
    RenderMode,
    RenderResult,
    RequestIndicator,
    ResourceList,
    ResourceRow,
    SafeUrl,
    Secret,
    Section,
    SegmentedControl,
    Select,
    SelectSlider,
    Sensitive,
    SessionTokenCsrf,
    Sidebar,
    Skeleton,
    SkipLink,
    Spacer,
    SplitView,
    Stack,
    StateView,
    Status,
    StorageQuotaExceeded,
    StyleRecipe,
    StyleScope,
    StyleSymbols,
    SubmitButton,
    Surface,
    Table,
    TableColumn,
    Tabs,
    Text,
    TextArea,
    TextInput,
    Theme,
    TimeInput,
    Timeline,
    Title,
    Toast,
    ToastHost,
    ToggleSwitch,
    Tooltip,
    TrustedHtml,
    TypeSchema,
    Typography,
    UrlPurpose,
    Video,
    ViewportHint,
    addressable,
    compile_css,
    compile_palette,
    contrast_diagnostics,
    contrast_ratio,
    get_icon,
    html,
    invalidate_tags,
    list_icons,
    redact_cookie_value,
    register_icon,
    render,
    resolve_color_mode,
    styles_from_manifest,
    trusted_svg,
)
from hedron_core.binding_plan import BoundaryBindingPlan
from hedron_core.builtins.forms_extra import DirectoryUploadFile, validate_directory_upload
from hedron_core.builtins.map_geo import MarkerSpec
from hedron_core.builtins.media import GalleryItem
from hedron_core.lifetime import DependencyLifetime, DependencyPlan
from hedron_core.scopes import RequiresScopes

if TYPE_CHECKING:
    from hedron.auth import OAuthHelper as OAuthHelper
    from hedron.auth import create_oauth_client as create_oauth_client
    from hedron.content import Markdown as Markdown
    from hedron.content import highlight_code as highlight_code
    from hedron.content import process_image as process_image
    from hedron.content import validate_email_address as validate_email_address
    from hedron_charts import AltairChart as AltairChart
    from hedron_charts import AreaChart as AreaChart
    from hedron_charts import BarChart as BarChart
    from hedron_charts import LineChart as LineChart
    from hedron_charts import MatplotlibChart as MatplotlibChart
    from hedron_charts import PlotlyChart as PlotlyChart
    from hedron_charts import ScatterChart as ScatterChart

_DATA_EXPORTS = frozenset(
    {
        "DataChanges",
        "DataEditor",
        "DataPage",
        "DataQuery",
        "DataSaveResult",
        "DataTable",
        "InMemoryDataSource",
    }
)
_CHART_EXPORTS = frozenset(
    {
        "AltairChart",
        "AreaChart",
        "BarChart",
        "LineChart",
        "MatplotlibChart",
        "PlotlyChart",
        "ScatterChart",
    }
)
_EXPERIMENTAL_EXPORTS = frozenset(
    {
        "ALLOW_MISSING_ORIGIN",
        "HX_PRELOADED",
        "NavigationPreloadPolicy",
        "SseResponse",
        "StreamingComponentResponse",
        "accept_page_session_channel",
        "apply_preload_headers",
        "evaluate_preload_request",
        "extension_script_tags",
        "job_status_sse_response",
        "origin_allowed",
        "send_region_update",
        "sse_response",
        "stream_chunked_list",
        "stream_document",
        "stream_tokens",
    }
)


def __getattr__(name: str) -> object:
    if name in _EXPERIMENTAL_EXPORTS:
        import warnings

        import hedron.experimental as _experimental

        warnings.warn(
            f"hedron.{name} is experimental; import from hedron.experimental "
            "(polling remains the Supported production fallback).",
            DeprecationWarning,
            stacklevel=2,
        )
        return getattr(_experimental, name)
    if name in _DATA_EXPORTS:
        try:
            import hedron_data as _hedron_data
        except ImportError as exc:  # pragma: no cover - exercised when extra missing
            raise ImportError(
                f"{name} requires the hedron-data package. "
                'Install with: pip install "hedron[data]" or pip install hedron-data'
            ) from exc
        return getattr(_hedron_data, name)
    if name in _CHART_EXPORTS:
        try:
            import hedron_charts as _hedron_charts
        except ImportError as exc:  # pragma: no cover
            raise ImportError(
                f"{name} requires the hedron-charts package. "
                'Install with: pip install "hedron[charts]>=0.29.0,<0.30" or '
                'pip install "hedron-charts>=0.1.10,<0.2". '
                "See https://hedron.readthedocs.io/en/latest/COMPATIBILITY/"
            ) from exc
        return getattr(_hedron_charts, name)
    if name == "Markdown":
        from hedron.content import Markdown

        return Markdown
    if name in {"validate_email_address", "highlight_code", "process_image"}:
        import hedron.content as _content

        return getattr(_content, name)
    if name in {"OAuthHelper", "create_oauth_client"}:
        import hedron.auth as _auth

        return getattr(_auth, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__version__ = "0.58.1"

# Stable + beta public facade. Live transports live in ``hedron.experimental``
# (compat attribute access retained via ``__getattr__``). Optional data/charts/auth
# extras remain lazy and are not part of the stable tier.
__all__ = [
    "__version__",
    "action_attrs",
    "ActionDock",
    "ActionGroup",
    "ActionHandle",
    "ActionRegistry",
    "addressable",
    "Alert",
    "apply_color_mode_cookie",
    "approved_headers",
    "AppShell",
    "Surface",
    "ResourceRow",
    "ResourceList",
    "NavStatus",
    "Identity",
    "GridItem",
    "EnvironmentBanner",
    "Brand",
    "Avatar",
    "AppFooter",
    "AccountSummary",
    "Aside",
    "AttrHost",
    "Audio",
    "AuthDenied",
    "AuthResult",
    "AuthSuccess",
    "Auto",
    "AutoForm",
    "await_if_needed",
    "Badge",
    "BottomDock",
    "BoundaryBindingPlan",
    "BoundFragment",
    "browser_context",
    "browser_context_from_request",
    "BrowserContext",
    "BrowserStorage",
    "BrowserStorageUnavailable",
    "Button",
    "ByteRangeNotSatisfiable",
    "cache_component",
    "cache_data",
    "CachePolicy",
    "CameraCapture",
    "Card",
    "Carousel",
    "case",
    "CatalogEntry",
    "CatalogVersionError",
    "ChatInput",
    "ChatMessage",
    "Checkbox",
    "ChipInput",
    "CircularProgress",
    "ClipboardCopy",
    "CodeBlock",
    "CodeViewer",
    "ColorInput",
    "ColorMode",
    "ColorModeToggle",
    "CommandHandler",
    "CommandResult",
    "compile_css",
    "compile_palette",
    "Component",
    "ComponentRef",
    "ComponentResponse",
    "ConfirmButton",
    "Container",
    "ContextMenu",
    "contrast_diagnostics",
    "contrast_ratio",
    "Control",
    "cookie_path_for_mount",
    "csrf_token_for_request",
    "CsrfField",
    "CsrfStrategy",
    "CsrfValidationError",
    "DashboardHistory",
    "DashboardWorkspace",
    "DateInput",
    "DateTimeInput",
    "default_interaction_policy",
    "DependencyLifetime",
    "DependencyPlan",
    "DependsOn",
    "DescriptionList",
    "DesignSystem",
    "Dialog",
    "Dialogue",
    "DialogueTurn",
    "DirectoryUpload",
    "DirectoryUploadFile",
    "Divider",
    "DoubleSubmitCookieCsrf",
    "download_all_zip",
    "DownloadButton",
    "ErrorState",
    "ExampleItem",
    "ExampleSet",
    "Expander",
    "FeedbackPolicy",
    "Field",
    "FileComponentResponse",
    "FileUpload",
    "FlowStep",
    "Footer",
    "Form",
    "form_sync_attrs",
    "FormBody",
    "FormErrors",
    "FormField",
    "FormGrid",
    "FormModel",
    "Fragment",
    "FragmentHandle",
    "FragmentHost",
    "FragmentRegion",
    "FragmentRegionError",
    "FragmentResponse",
    "Gallery",
    "GalleryItem",
    "gather",
    "GeoJSONLayer",
    "GeolocationButton",
    "GeolocationHint",
    "get_icon",
    "Grid",
    "Head",
    "Header",
    "Heading",
    "Hedron",
    "hedron_response",
    "HedronRoute",
    "HedronRouter",
    "Help",
    "HelpInspector",
    "HTML",
    "html",
    "htmx_context",
    "htmx_request",
    "HtmxLink",
    "HtmxRequest",
    "Hx",
    "Icon",
    "IconButton",
    "IFrame",
    "Image",
    "InferenceInterface",
    "InferencePolicy",
    "InferenceWorkflow",
    "InfiniteScroll",
    "Inline",
    "InstanceKey",
    "InteractionCatalog",
    "InteractionManifest",
    "InteractionPolicy",
    "InteractionRecorder",
    "InteractionResult",
    "invalidate_tags",
    "JobScope",
    "JobScopeProvider",
    "JSONViewer",
    "Label",
    "Lazy",
    "Link",
    "LinkButton",
    "List",
    "list_icons",
    "Loading",
    "LoginCsrfField",
    "Logo",
    "Main",
    "MainPanel",
    "Map",
    "MarkerSpec",
    "Math",
    "media_file_response",
    "PollPolicy",
    "RateLimitPolicy",
    "SessionAuthFlow",
    "SessionRotationPolicy",
    "StyleRecipe",
    "StyleScope",
    "TaskFlow",
    "TaskUnavailablePolicy",
    "UploadFlow",
    "MenuButton",
    "merge_htmx_headers",
    "Metric",
    "MicrophoneCapture",
    "Model",
    "ModelDemo",
    "mount_from_request",
    "mount_hedron_static",
    "MountPath",
    "MultiSelect",
    "Nav",
    "NavLink",
    "normalize_mount_path",
    "NumberInput",
    "oob_swap",
    "OobHost",
    "OobUpdate",
    "OutcomeMap",
    "PackageProjection",
    "Page",
    "PageHeader",
    "PageIcon",
    "PageResponse",
    "Pagination",
    "ParameterViewer",
    "parse_byte_range",
    "Patch",
    "patches",
    "PatchSet",
    "PdfViewer",
    "Pills",
    "Poll",
    "Popover",
    "PredictionFeedback",
    "PredictionLabel",
    "PredictionScore",
    "prefix_local_path",
    "ProcessFlow",
    "Progress",
    "ProjectionCapability",
    "Props",
    "RadioGroup",
    "RangeInput",
    "RatingInput",
    "read_color_mode_preference",
    "RecordedExchange",
    "RecordingSnippet",
    "redact_cookie_value",
    "redirect_external",
    "redirect_htmx",
    "redirect_local",
    "Refresh",
    "refresh",
    "RefreshableView",
    "RefreshButton",
    "Refreshes",
    "RefreshIntent",
    "register_icon",
    "RegisteredAction",
    "render",
    "render_component_response",
    "render_interaction",
    "RenderContext",
    "RenderMode",
    "RenderResult",
    "RequestIndicator",
    "RequiresScopes",
    "resolve_color_mode",
    "resolve_mount_path",
    "resolve_mount_path_from_environ",
    "resolve_route_path",
    "resolved_theme_from_request",
    "retarget",
    "run_sync",
    "safe_download_response",
    "SafeUrl",
    "ScreenHandle",
    "ScreenLayout",
    "Secret",
    "Section",
    "SecurityHeadersPolicy",
    "SecurityPolicy",
    "SecurityProfile",
    "SegmentedControl",
    "Select",
    "SelectSlider",
    "Sensitive",
    "session_state",
    "SessionState",
    "SessionTokenCsrf",
    "Sidebar",
    "Skeleton",
    "SkipLink",
    "Spacer",
    "SplitView",
    "MasterDetail",
    "Stack",
    "StateView",
    "Status",
    "StorageQuotaExceeded",
    "styles_from_manifest",
    "StyleSymbols",
    "SubmitButton",
    "swap",
    "swap_oob",
    "Table",
    "TableColumn",
    "Tabs",
    "Text",
    "TextArea",
    "TextInput",
    "Theme",
    "TimeInput",
    "Timeline",
    "Title",
    "Toast",
    "ToastHost",
    "ToggleSwitch",
    "Tooltip",
    "trusted_svg",
    "TrustedHtml",
    "TypeSchema",
    "Typography",
    "Updates",
    "UrlPurpose",
    "validate_directory_upload",
    "Video",
    "ViewParams",
    "ViewportHint",
]
