"""Import-time registration of first-party built-in components."""

from __future__ import annotations

from hedron_core.auto import Auto
from hedron_core.builtins import (
    AccountSummary,
    ActionDock,
    ActionGroup,
    Alert,
    AmbientBackdrop,
    AppFooter,
    AppShell,
    Aside,
    AsyncRegion,
    AttrHost,
    Audio,
    Avatar,
    Badge,
    BottomDock,
    Brand,
    BusyRegion,
    Button,
    CameraCapture,
    Card,
    Carousel,
    ChatMessage,
    Checkbox,
    ChipInput,
    CircularProgress,
    ClipboardCopy,
    CodeBlock,
    CodeViewer,
    ColorInput,
    ConfirmButton,
    ConnectorFlow,
    ConnectorNode,
    ConnectorTrack,
    Container,
    ContextMenu,
    CsrfField,
    DateInput,
    DateTimeInput,
    DescriptionList,
    Dialog,
    Dialogue,
    DirectoryUpload,
    Divider,
    EnvironmentBanner,
    Expander,
    FlowStep,
    Footer,
    Form,
    FormErrors,
    FormField,
    FormGrid,
    Fragment,
    Gallery,
    GeolocationButton,
    GeolocationHint,
    Grid,
    GridItem,
    Head,
    Header,
    Heading,
    Help,
    HelpInspector,
    HtmxLink,
    Hx,
    Icon,
    IconButton,
    Identity,
    IFrame,
    Image,
    Inline,
    JSONViewer,
    Label,
    Link,
    LinkButton,
    List,
    Logo,
    Main,
    MainPanel,
    Map,
    MasterDetail,
    Math,
    MenuButton,
    Metric,
    MicrophoneCapture,
    MultiSelect,
    Nav,
    NavGroup,
    NavStatus,
    NumberInput,
    OobHost,
    Page,
    PageHeader,
    PageIcon,
    ParameterViewer,
    PdfViewer,
    Pills,
    Popover,
    PredictionLabel,
    ProcessFlow,
    Progress,
    RadioGroup,
    RangeInput,
    RatingInput,
    RequestIndicator,
    ResourceList,
    ResourceRow,
    ScrollRegion,
    Section,
    SegmentedControl,
    Select,
    SelectSlider,
    Sidebar,
    Skeleton,
    SkipLink,
    Spacer,
    SplitView,
    SseRegion,
    SseTrigger,
    Stack,
    StateView,
    Status,
    StyleScope,
    SubmitButton,
    Surface,
    SwapReveal,
    Table,
    Tabs,
    Text,
    TextArea,
    TextInput,
    ThemePicker,
    TimeInput,
    Timeline,
    Title,
    Toast,
    ToastHost,
    ToggleSwitch,
    Tooltip,
    Typography,
    Video,
)
from hedron_core.color_mode import ColorModeToggle
from hedron_core.registry import register_component
from hedron_core.theme_platform import ComponentThemeContract, register_component_theme_contract


def register_builtins() -> None:
    """Register every first-party widget with the component catalog."""
    for cls in (
        Page,
        Fragment,
        Head,
        Title,
        Header,
        Main,
        Nav,
        Aside,
        Footer,
        Section,
        Container,
        Stack,
        Inline,
        Grid,
        Divider,
        Spacer,
        SseRegion,
        SseTrigger,
        Heading,
        Text,
        Link,
        HtmxLink,
        OobHost,
        AttrHost,
        MainPanel,
        NavGroup,
        AppShell,
        Surface,
        ResourceRow,
        ResourceList,
        NavStatus,
        Identity,
        GridItem,
        EnvironmentBanner,
        Brand,
        Avatar,
        AppFooter,
        AccountSummary,
        AsyncRegion,
        Image,
        CodeBlock,
        List,
        DescriptionList,
        Table,
        Audio,
        Video,
        PdfViewer,
        Gallery,
        Logo,
        PageIcon,
        MicrophoneCapture,
        CameraCapture,
        PredictionLabel,
        ParameterViewer,
        Dialogue,
        Metric,
        CodeViewer,
        JSONViewer,
        Progress,
        CircularProgress,
        Status,
        StyleScope,
        Toast,
        Expander,
        Tabs,
        Sidebar,
        ColorModeToggle,
        Auto,
        Card,
        Badge,
        Alert,
        AmbientBackdrop,
        Skeleton,
        Map,
        Button,
        LinkButton,
        IconButton,
        Form,
        CsrfField,
        Hx,
        FormField,
        Label,
        TextInput,
        TextArea,
        Select,
        Checkbox,
        RadioGroup,
        SubmitButton,
        FormErrors,
        SwapReveal,
        BusyRegion,
        NumberInput,
        RangeInput,
        DateInput,
        TimeInput,
        DateTimeInput,
        MultiSelect,
        ToggleSwitch,
        SegmentedControl,
        Pills,
        ColorInput,
        RatingInput,
        ChipInput,
        MenuButton,
        SelectSlider,
        DirectoryUpload,
        Carousel,
        Timeline,
        ContextMenu,
        Popover,
        ActionDock,
        BottomDock,
        Tooltip,
        Help,
        ConfirmButton,
        ClipboardCopy,
        Math,
        HelpInspector,
        IFrame,
        GeolocationButton,
        GeolocationHint,
        Dialog,
        ChatMessage,
        PageHeader,
        SplitView,
        MasterDetail,
        FormGrid,
        ActionGroup,
        SkipLink,
        RequestIndicator,
        ProcessFlow,
        ConnectorFlow,
        ConnectorNode,
        ConnectorTrack,
        ScrollRegion,
        ToastHost,
        ThemePicker,
        FlowStep,
        Icon,
        Typography,
        StateView,
    ):
        logical = (
            f"{getattr(cls, 'distribution', 'hedron-core')}:"
            f"{cls.__module__}.{getattr(cls, 'logical_name', cls.__name__)}"
        )
        register_component(
            logical_id=logical,
            name=getattr(cls, "logical_name", cls.__name__) or cls.__name__,
            module=cls.__module__,
            distribution=getattr(cls, "distribution", "hedron-core"),
            props_model=getattr(cls, "props_type", type(None)).__name__,
            slots=getattr(cls, "slots", {}),
            accessibility_notes="Uses native semantic HTML without JavaScript.",
        )
    # Public alias discoverable via CLI inspect/eject.
    register_component(
        logical_id="hedron-core:hedron_core.builtins.shell.NavLink",
        name="NavLink",
        module="hedron_core.builtins.shell",
        distribution="hedron-core",
        props_model="HtmxLinkProps",
        slots={},
        accessibility_notes="Alias of HtmxLink for shell navigation.",
    )
    for contract in (
        ComponentThemeContract(
            "Brand",
            parts=("mark", "copy", "name", "subtitle"),
            roles=("text", "muted-text"),
            required_tokens=("color.fg", "color.muted"),
            contrast_relationships=(
                {"foreground": "color.fg", "background": "color.bg"},
                {"foreground": "color.muted", "background": "color.bg"},
            ),
            accessibility_behavior={"subtitle": "wrap-or-bounded-overflow"},
            fallback_policy={"forced-colors": "system-colors", "print": "flow"},
            profile="core",
        ),
        ComponentThemeContract(
            "ToastHost",
            parts=("host",),
            states=("placement",),
            roles=("surface", "announcement"),
            required_tokens=("color.bg", "color.fg", "color.focus"),
            contrast_relationships=(
                {"foreground": "color.fg", "background": "color.bg"},
                {"foreground": "color.focus", "background": "color.bg"},
            ),
            accessibility_behavior={"announcement": "single-live-region-owner"},
            fallback_policy={"print": "flow", "reduced-motion": "no-transition"},
            profile="core",
        ),
        ComponentThemeContract(
            "ConnectorFlow",
            parts=("canvas",),
            states=("background", "overflow"),
            roles=("surface", "accent", "decoration"),
            required_tokens=("color.bg", "color.surface", "color.accent"),
            contrast_relationships=({"foreground": "color.accent", "background": "color.surface"},),
            accessibility_behavior={"decoration": "non-semantic"},
            fallback_policy={"forced-colors": "remove-decoration", "print": "remove-decoration"},
            profile="workflow",
        ),
        ComponentThemeContract(
            "ScrollRegion",
            parts=("region",),
            states=("axis", "size"),
            roles=("content", "focus"),
            required_tokens=("color.fg", "color.focus"),
            contrast_relationships=({"foreground": "color.focus", "background": "color.bg"},),
            accessibility_behavior={"focus": "conditional-container-focus"},
            fallback_policy={"print": "visible-overflow"},
            profile="core",
        ),
        ComponentThemeContract(
            "AccountSummary",
            parts=("avatar", "identity", "name", "email", "actions"),
            states=("signed-in", "signed-out", "overflow"),
            roles=("identity", "actions", "muted-text"),
            required_tokens=("color.fg", "color.muted", "color.surface"),
            contrast_relationships=(
                {"foreground": "color.fg", "background": "color.surface"},
                {"foreground": "color.muted", "background": "color.surface"},
            ),
            accessibility_behavior={"actions": "keyboard-reachable"},
            fallback_policy={"print": "identity-only", "forced-colors": "system-colors"},
            profile="core",
        ),
        ComponentThemeContract(
            "Button",
            parts=("label", "icon", "busy-indicator"),
            states=("hover", "focus", "disabled", "busy", "pressed"),
            variants=("default", "primary", "danger", "quiet"),
            roles=("control", "focus", "status"),
            required_tokens=("color.fg", "color.accent", "color.focus", "motion.duration"),
            contrast_relationships=(
                {"foreground": "color.accent", "background": "color.bg"},
                {"foreground": "color.focus", "background": "color.bg"},
            ),
            accessibility_behavior={"busy-indicator": "aria-busy-with-label"},
            fallback_policy={"reduced-motion": "no-transition", "forced-colors": "system-colors"},
            profile="core",
        ),
        ComponentThemeContract(
            "Card",
            parts=("header", "body", "footer"),
            states=("default", "interactive", "selected"),
            roles=("surface", "content"),
            required_tokens=("color.surface", "color.fg", "color.muted"),
            contrast_relationships=(
                {"foreground": "color.fg", "background": "color.surface"},
                {"foreground": "color.muted", "background": "color.surface"},
            ),
            accessibility_behavior={"selected": "aria-selected-when-owned"},
            fallback_policy={"print": "solid-surface", "reduced-transparency": "solid-surface"},
            profile="core",
        ),
        ComponentThemeContract(
            "Tabs",
            parts=("tablist", "tab", "panel"),
            states=("selected", "focus", "disabled", "overflow"),
            variants=("default", "scroll", "stretch", "compact"),
            roles=("navigation", "control", "content"),
            required_tokens=("color.fg", "color.accent", "color.focus"),
            contrast_relationships=(
                {"foreground": "color.fg", "background": "color.bg"},
                {"foreground": "color.accent", "background": "color.bg"},
            ),
            accessibility_behavior={"tablist": "aria-tablist-roving-focus"},
            fallback_policy={"print": "all-panels", "forced-colors": "border-state"},
            profile="core",
        ),
        ComponentThemeContract(
            "Dialog",
            parts=("title", "body", "actions", "close"),
            states=("open", "closing", "busy"),
            roles=("dialog", "surface", "focus"),
            required_tokens=("color.surface", "color.fg", "color.focus", "motion.duration"),
            contrast_relationships=(
                {"foreground": "color.fg", "background": "color.surface"},
                {"foreground": "color.focus", "background": "color.surface"},
            ),
            accessibility_behavior={"dialog": "labelled-and-focus-contained"},
            fallback_policy={"reduced-motion": "no-transition", "print": "flow"},
            profile="core",
        ),
    ):
        register_component_theme_contract(contract)
