#!/usr/bin/env python3
"""Generate and verify the direct dependency matrix for Stable 1.0 packages."""

from __future__ import annotations

import argparse
import importlib.metadata
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
SUPPORT = ROOT / "release/support-matrix.toml"
REQUIREMENTS = ROOT / "release/stable-dependencies.txt"


def _project(path: Path) -> dict[str, object]:
    return tomllib.loads(path.read_text(encoding="utf-8"))["project"]


def stable_requirements() -> dict[str, SpecifierSet]:
    support = tomllib.loads(SUPPORT.read_text(encoding="utf-8"))
    package_contracts = support["packages"]
    workspace_names = {
        canonicalize_name(str(_project(path)["name"]))
        for path in (ROOT / "packages").glob("*/pyproject.toml")
    }
    clauses: dict[str, set[str]] = defaultdict(set)
    for distribution, contract in package_contracts.items():
        if contract.get("maturity") != "stable":
            continue
        project = _project(ROOT / "packages" / distribution / "pyproject.toml")
        for raw in project.get("dependencies", []):
            requirement = Requirement(str(raw))
            name = canonicalize_name(requirement.name)
            if name in workspace_names:
                continue
            clauses[name].update(str(requirement.specifier).split(","))

    release = support["release"]
    for name in ("fastapi", "starlette", "pydantic", "uvicorn"):
        clauses[name].update(str(SpecifierSet(str(release[name]))).split(","))
    return {
        name: SpecifierSet(",".join(sorted(filter(None, specifiers))))
        for name, specifiers in clauses.items()
    }


def rendered_requirements() -> str:
    header = (
        "# Generated by scripts/check_stable_dependency_bounds.py; do not edit manually.\n"
        "# These direct requirements are resolved with lowest-direct and highest lanes.\n"
    )
    rows = [f"{name}{specifier}" for name, specifier in sorted(stable_requirements().items())]
    return header + "\n".join(rows) + "\n"


def check_file() -> list[str]:
    expected = rendered_requirements()
    actual = REQUIREMENTS.read_text(encoding="utf-8") if REQUIREMENTS.is_file() else ""
    return [] if actual == expected else [f"{REQUIREMENTS.relative_to(ROOT)} is stale"]


def verify_installed(lane: str) -> list[str]:
    errors: list[str] = []
    versions: list[str] = []
    for name, specifier in sorted(stable_requirements().items()):
        try:
            installed = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            errors.append(f"{name}: not installed in {lane} dependency environment")
            continue
        versions.append(f"{name}=={installed}")
        if installed not in specifier:
            errors.append(f"{name}=={installed} is outside Stable range {specifier}")
    print(f"{lane} direct versions: " + ", ".join(versions))
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-installed", choices=("minimum", "latest"))
    args = parser.parse_args(argv)
    if args.write:
        REQUIREMENTS.write_text(rendered_requirements(), encoding="utf-8")
    errors: list[str] = []
    if args.check:
        errors.extend(check_file())
    if args.verify_installed:
        errors.extend(verify_installed(args.verify_installed))
    if not (args.write or args.check or args.verify_installed):
        parser.error("choose --write, --check, or --verify-installed")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print("ok: Stable direct dependency bounds")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
