#!/usr/bin/env python3
"""Generate the public Edron export index from ``edron.__all__``."""

from __future__ import annotations

import argparse
import inspect
from pathlib import Path

import edron

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "api" / "EDRON_EXPORTS.md"


def render() -> str:
    rows: list[tuple[str, str]] = []
    for name in sorted(edron.__all__, key=str.casefold):
        value = getattr(edron, name)
        owner = inspect.getmodule(value)
        module = owner.__name__ if owner is not None else type(value).__module__
        rows.append((name, module))

    lines = [
        "---",
        "description: Generated inventory of every public Edron 1.0 export.",
        "---",
        "",
        "# Edron public export index",
        "",
        "This file is generated by `scripts/generate_edron_api_index.py`. Do not edit it by hand.",
        "Use [Edron API by task](EDRON_REFERENCE.md) for concepts and",
        "[Edron symbols](EDRON_AUTODOC.md) for signatures and docstrings.",
        "",
        "| Symbol | Owning module |",
        "|---|---|",
    ]
    lines.extend(f"| `{name}` | `{module}` |" for name, module in rows)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "docs/api/EDRON_EXPORTS.md is stale; run "
                "uv run python scripts/generate_edron_api_index.py"
            )
        print(f"ok: {OUTPUT.relative_to(ROOT)} has {len(edron.__all__)} exports")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(edron.__all__)} exports")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
