"""Sync Demo/Code tabs in guide markdown from ``docs/demos/runnable/``.

Component pages are regenerated by ``generate_component_docs.py``. This script
keeps hand-authored guide / getting-started / example pages aligned with the
same runnable ``app.py`` sources.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

# path relative to docs/ → (sim_id, demo_blurb)
GUIDE_TABS: tuple[tuple[str, str, str], ...] = (
    (
        "guides/htmx-interactions.md",
        "htmx-interactions",
        "Multi-region refresh plus an allowlist miss — docs simulation (no live server).",
    ),
    (
        "guides/forms-and-actions.md",
        "forms-invite",
        "Invalid email → FormErrors fragment. Valid email → success region. Docs simulation.",
    ),
    (
        "guides/forms-and-actions.md",
        "pe-paths",
        "HTMX fragment vs full-page confirmation path (PE-019). Docs simulation.",
    ),
    (
        "guides/live-interaction.md",
        "live-poll",
        "Bounded poll — each click advances one step (four steps, then wraps). Docs simulation.",
    ),
    (
        "guides/cookbook.md",
        "cookbook-oob",
        "One click updates the primary region and an OOB host — docs simulation.",
    ),
    (
        "guides/troubleshooting.md",
        "allowlist-403",
        "Correct target swaps; wrong `#panel` returns 403 with no swap. Docs simulation.",
    ),
    (
        "guides/charts-and-htmx.md",
        "charts-htmx",
        "Refresh advances a short chart sequence (then wraps). Docs simulation.",
    ),
    (
        "guides/mutations.md",
        "mutations-htmx",
        "HTMX fragment POST — submit swaps the declared result region. Docs simulation.",
    ),
    (
        "guides/minimal-form.md",
        "minimal-form",
        "Classic POST — confirmation replaces the notes region. Docs simulation.",
    ),
    (
        "guides/authentication.md",
        "auth-login",
        "Wrong password → soft redirect to /login?error=1. ada / correct-horse → signed-in panel. Docs simulation.",
    ),
    (
        "guides/security.md",
        "csrf-guard",
        "POST with CSRF succeeds; missing token → 403. Docs simulation.",
    ),
    (
        "guides/data-apps.md",
        "data-table-filter",
        "Filter chips swap the declared table region. Docs simulation.",
    ),
    (
        "guides/jobs-celery-rq.md",
        "jobs-poll",
        "Bounded job poll — each click advances one status step. Docs simulation.",
    ),
    (
        "guides/multi-tenant.md",
        "tenant-deny",
        "Same-tenant poll succeeds; other tenant → 404 without leaking. Docs simulation.",
    ),
    (
        "guides/accessibility.md",
        "pe-paths",
        "HTMX fragment vs full-page confirmation path (PE-019). Docs simulation.",
    ),
    (
        "examples/crud-tutorial.md",
        "minimal-form",
        "Classic POST — confirmation replaces the notes region. Docs simulation.",
    ),
    (
        "examples/crud-tutorial.md",
        "mutations-htmx",
        "HTMX fragment POST — submit swaps the declared result region. Docs simulation.",
    ),
    (
        "examples/crud-tutorial.md",
        "crud-notes",
        "Miniature list — add multiple notes, then delete any row. Docs simulation.",
    ),
    (
        "examples/notes-sqlalchemy.md",
        "crud-notes",
        "Same list pattern as the notes recipe — add and delete rows. Docs simulation "
        "(in-memory; the real recipe uses SQLAlchemy + SQLite).",
    ),
    (
        "examples/session-auth.md",
        "auth-login",
        "Wrong password → soft redirect to /login?error=1. ada / correct-horse → signed-in panel. Docs simulation.",
    ),
    (
        "examples/file-upload.md",
        "file-upload",
        "Allowlisted .txt succeeds; .exe is rejected. Docs simulation "
        "(canned files, no disk picker).",
    ),
    (
        "examples/jobs-poll.md",
        "jobs-poll",
        "Bounded job poll — each click advances one status step. Docs simulation.",
    ),
    (
        "examples/reference-app.md",
        "auth-login",
        "Wrong password → 401. ada / correct-horse → signed-in panel. Docs simulation.",
    ),
    (
        "examples/reference-app.md",
        "csrf-guard",
        "POST with CSRF succeeds; missing token → 403. Docs simulation.",
    ),
    (
        "examples/reference-app.md",
        "crud-notes",
        "Fragment list refresh pattern used throughout the reference app. Docs simulation.",
    ),
    (
        "examples/reference-app.md",
        "charts-htmx",
        "Refresh advances a short chart sequence (then wraps). Docs simulation.",
    ),
    (
        "examples/single-file.md",
        "hello-refresh",
        "Docs simulation — click Refresh status for an HTMX-style fragment swap (no server).",
    ),
    (
        "getting-started/core-concepts.md",
        "core-concepts-modes",
        "Toggle the response shape — docs simulation only.",
    ),
    (
        "getting-started/quickstart.md",
        "hello-refresh-quickstart",
        "Same fragment swap as the scaffold — docs simulation (no server).",
    ),
    (
        "index.md",
        "hello-refresh",
        "Docs simulation — no live server. Click **Refresh status** to swap the fragment.",
    ),
)

_TAB_BLOCK = re.compile(
    r'=== "Demo"\n\n.*?\n=== "Code"\n\n.*?    ```\n',
    re.S,
)

_CODE_BLURBS: dict[tuple[str, str], str] = {
    (
        "guides/authentication.md",
        "auth-login",
    ): (
        "Same `app.py` as the [session-auth recipe](../examples/session-auth.md): "
        "soft redirects, CSRF-safe sign-in, and logout. The Demo tab is a simplified view:"
    ),
    (
        "examples/notes-sqlalchemy.md",
        "crud-notes",
    ): (
        "In-memory listing that reproduces the demo. The runnable recipe downloaded "
        "below replaces the list with SQLAlchemy + SQLite persistence:"
    ),
    (
        "examples/session-auth.md",
        "auth-login",
    ): (
        "Real recipe listing with the documented soft redirect and logout flow. "
        "The Demo tab is a simplified view:"
    ),
    (
        "examples/jobs-poll.md",
        "jobs-poll",
    ): (
        "Real recipe listing using `enqueue_durable`, `Poll`, and scoped job status. "
        "The Demo tab is a simplified bounded view:"
    ),
}

_CODE_SOURCES: dict[str, Path] = {
    "guides/authentication.md": ROOT / "examples" / "session-auth" / "app.py",
    "examples/session-auth.md": ROOT / "examples" / "session-auth" / "app.py",
    "examples/jobs-poll.md": ROOT / "examples" / "jobs-poll" / "app.py",
}


def _sync_file(
    path: Path,
    sim_id: str,
    blurb: str,
    *,
    check: bool,
) -> bool:
    sys.path.insert(0, str(DOCS))
    from demos.tabs import format_demo_code_tabs

    rel = path.relative_to(DOCS).as_posix()
    if rel == "examples/reference-app.md":
        code_blurb = (
            "Focused runnable listing for this pattern—not the full reference app. "
            "Use the run instructions below for the production archetype:"
        )
    else:
        code_blurb = _CODE_BLURBS.get(
            (rel, sim_id),
            (
                "What `hedron new` writes as `app.py` (the real app, not the docs simulator):"
                if sim_id in {"hello-refresh", "hello-refresh-quickstart"}
                else (
                    "Minimal runnable `app.py` that reproduces this demo "
                    "(real Hedron, not the docs simulator):"
                )
            ),
        )
    tabs = (
        format_demo_code_tabs(
            sim_id,
            demo_blurb=blurb,
            code_blurb=code_blurb,
            code=(_CODE_SOURCES[rel].read_text(encoding="utf-8") if rel in _CODE_SOURCES else None),
        ).rstrip()
        + "\n"
    )
    text = path.read_text(encoding="utf-8")
    marker = f"<!-- hedron-sim:{sim_id} -->"
    if marker not in text:
        print(f"missing marker {sim_id} in {path.relative_to(ROOT)}")
        return True

    match = None
    for candidate in _TAB_BLOCK.finditer(text):
        if marker in candidate.group(0):
            match = candidate
            break
    if match is None:
        # Insert Demo/Code tabs immediately after a bare marker line.
        bare = re.search(
            rf"(^### Try it \(simulated\)\n\n)({re.escape(marker)}\n)",
            text,
            flags=re.M,
        )
        if bare is None:
            bare = re.search(rf"(^{re.escape(marker)}\n)", text, flags=re.M)
            if bare is None:
                print(f"no existing Demo/Code tabs for {path.relative_to(ROOT)}; skip auto-insert")
                return True
            new_text = text[: bare.start()] + tabs + text[bare.end() :]
        else:
            new_text = text[: bare.start(2)] + tabs + text[bare.end(2) :]
        if check:
            print(f"out of date: {path.relative_to(ROOT)}")
            return True
        path.write_text(new_text, encoding="utf-8")
        print(f"inserted tabs {path.relative_to(ROOT)}")
        return True

    new_text = text[: match.start()] + tabs + text[match.end() :]
    if new_text == text:
        return False
    if check:
        print(f"out of date: {path.relative_to(ROOT)}")
        return True
    path.write_text(new_text, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    dirty = False
    for rel, sim_id, blurb in GUIDE_TABS:
        path = DOCS / rel
        if _sync_file(path, sim_id, blurb, check=args.check):
            dirty = True
    if args.check and dirty:
        return 1
    if args.check:
        print("demo code tabs up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
