"""Sync Demo/Code tabs in guide markdown from ``docs/demos/runnable/``.

Component pages are regenerated by ``generate_component_docs.py``. This script
keeps hand-authored guide / getting-started / example pages aligned with the
same runnable ``app.py`` sources.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

# path relative to docs/ → (sim_id, demo_blurb)
GUIDE_TABS: tuple[tuple[str, str, str], ...] = (
    (
        "guides/htmx-interactions.md",
        "htmx-interactions",
        "Multi-region refresh plus an allowlist miss — docs simulation (no live server).",
    ),
    (
        "guides/forms-and-actions.md",
        "forms-invite",
        "Invalid email → FormErrors fragment. Valid email → success region. Docs simulation.",
    ),
    (
        "guides/live-interaction.md",
        "live-poll",
        "Bounded poll — each click advances one step (four steps, then wraps). Docs simulation.",
    ),
    (
        "guides/cookbook.md",
        "cookbook-oob",
        "One click updates the primary region and an OOB host — docs simulation.",
    ),
    (
        "guides/troubleshooting.md",
        "allowlist-403",
        "Correct target swaps; wrong `#panel` returns 403 with no swap. Docs simulation.",
    ),
    (
        "guides/charts-and-htmx.md",
        "charts-htmx",
        "Refresh advances a short chart sequence (then wraps). Docs simulation.",
    ),
    (
        "guides/mutations.md",
        "mutations-htmx",
        "HTMX fragment POST — submit swaps the declared result region. Docs simulation.",
    ),
    (
        "examples/crud-tutorial.md",
        "crud-notes",
        "Miniature list — type a note, add it, then delete it. Docs simulation.",
    ),
    (
        "getting-started/core-concepts.md",
        "core-concepts-modes",
        "Toggle the response shape — docs simulation only.",
    ),
    (
        "getting-started/quickstart.md",
        "hello-refresh-quickstart",
        "Same fragment swap as the scaffold — docs simulation (no server).",
    ),
    (
        "index.md",
        "hello-refresh",
        "Docs simulation — no live server. Click **Refresh status** to swap the fragment.",
    ),
)

_TAB_BLOCK = re.compile(
    r'=== "Demo"\n\n.*?\n=== "Code"\n\n.*?    ```\n',
    re.S,
)


def _sync_file(
    path: Path,
    sim_id: str,
    blurb: str,
    *,
    check: bool,
) -> bool:
    sys.path.insert(0, str(DOCS))
    from demos.tabs import format_demo_code_tabs

    code_blurb = (
        "What `hedron new` writes as `app.py` (the real app, not the docs simulator):"
        if sim_id in {"hello-refresh", "hello-refresh-quickstart"}
        else (
            "Minimal runnable `app.py` that reproduces this demo "
            "(real Hedron, not the docs simulator):"
        )
    )
    tabs = (
        format_demo_code_tabs(
            sim_id,
            demo_blurb=blurb,
            code_blurb=code_blurb,
        ).rstrip()
        + "\n"
    )
    text = path.read_text(encoding="utf-8")
    marker = f"<!-- hedron-sim:{sim_id} -->"
    if marker not in text:
        print(f"missing marker {sim_id} in {path.relative_to(ROOT)}")
        return True

    match = None
    for candidate in _TAB_BLOCK.finditer(text):
        if marker in candidate.group(0):
            match = candidate
            break
    if match is None:
        # Insert tabs by replacing a bare marker (and optional preceding prose line).
        print(f"no existing Demo/Code tabs for {path.relative_to(ROOT)}; skip auto-insert")
        return True

    new_text = text[: match.start()] + tabs + text[match.end() :]
    if new_text == text:
        return False
    if check:
        print(f"out of date: {path.relative_to(ROOT)}")
        return True
    path.write_text(new_text, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    dirty = False
    for rel, sim_id, blurb in GUIDE_TABS:
        path = DOCS / rel
        if _sync_file(path, sim_id, blurb, check=args.check):
            dirty = True
    if args.check and dirty:
        return 1
    if args.check:
        print("demo code tabs up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
