"""Scaffold for ``hedron new element``."""

from __future__ import annotations

import json
import re
from pathlib import Path

from hedron.cli.discovery import _scaffold_dep


def _scaffold_element(name: str, dest: Path) -> int:
    distribution = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "element-plugin"
    package_name = re.sub(r"\W+", "_", name.lower()).strip("_") or "element_plugin"
    if package_name[0].isdigit():
        package_name = f"element_{package_name}"
    tag_name = distribution if "-" in distribution else f"ext-{distribution}"
    logical_id = f"{distribution}:{tag_name}"
    module_asset_id = f"{distribution}:{tag_name}.mjs"
    css_asset_id = f"{distribution}:{tag_name}.css"
    package_dir = dest / "src" / package_name
    static_dir = package_dir / "static"
    tests_dir = dest / "tests"
    examples_dir = dest / "examples"
    for directory in (static_dir, tests_dir, examples_dir):
        directory.mkdir(parents=True, exist_ok=True)

    (dest / "pyproject.toml").write_text(
        f'''[project]
name = "{distribution}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "{_scaffold_dep("hedron-core")}",
    "{_scaffold_dep("hedron-elements")}",
]

[project.entry-points."hedron.plugins"]
{package_name} = "{package_name}.plugin:register"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{package_name}"]
''',
        encoding="utf-8",
    )
    (package_dir / "__init__.py").write_text("", encoding="utf-8")
    (package_dir / "plugin.py").write_text(
        f'''"""Hedron element plugin generated by ``hedron new element``."""

from hashlib import sha256
from pathlib import Path

from hedron_core.plugins import PluginCapabilities, PluginContext, PluginMeta

_META = PluginMeta(
    name="{package_name}",
    version="0.1.0",
    distribution="{distribution}",
    hedron_version=">=0.48,<0.49",
    capabilities=PluginCapabilities(browser_js=True, styles=True, assets=True),
)

_STATIC = Path(__file__).parent / "static"
_TAG = "{tag_name}"


def _digest(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def register(ctx: PluginContext) -> None:
    module = _STATIC / f"{{_TAG}}.mjs"
    styles = _STATIC / f"{{_TAG}}.css"
    ctx.register_asset(
        logical_id="{module_asset_id}",
        kind="module",
        path=str(module),
        digest=_digest(module),
        content_type="text/javascript",
    )
    ctx.register_asset(
        logical_id="{css_asset_id}",
        kind="css",
        path=str(styles),
        digest=_digest(styles),
        content_type="text/css",
    )
    ctx.register_browser_module(
        logical_id="{distribution}:browser",
        tag_name=_TAG,
        module_path=str(module),
    )
    ctx.register_element_definition(
        logical_id="{logical_id}",
        tag_name=_TAG,
        abi_version=1,
        module_asset_id="{module_asset_id}",
        attributes=("status",),
        events=("{tag_name}-change",),
        lifecycle={{"connect": "idempotent", "disconnect": "dispose"}},
        fallback={{"js_off": "server content remains visible"}},
        a11y_contract={{}},
        resources=("{css_asset_id}",),
    )


register.PLUGIN_META = _META
''',
        encoding="utf-8",
    )
    (static_dir / f"{tag_name}.mjs").write_text(
        f'''class Element extends HTMLElement {{
  connectedCallback() {{
    this.dataset.hedronElement = "{tag_name}";
  }}
}}

if (!customElements.get("{tag_name}")) {{
  customElements.define("{tag_name}", Element);
}}
''',
        encoding="utf-8",
    )
    (static_dir / f"{tag_name}.css").write_text(
        f"{tag_name} {{\n  display: block;\n}}\n",
        encoding="utf-8",
    )
    (tests_dir / "test_element.py").write_text(
        f'''from hedron_core import get_registry, reset_registry_for_tests
from hedron_core.plugins import PluginContext

from {package_name}.plugin import PLUGIN_META, register


def test_element_registers() -> None:
    reset_registry_for_tests()
    register(PluginContext(PLUGIN_META))
    assert get_registry().get_element_definition("{logical_id}") is not None
''',
        encoding="utf-8",
    )
    (examples_dir / "README.md").write_text(
        f"# {tag_name} example\n\nRender `<{tag_name}>Fallback content</{tag_name}>`.\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "created": str(dest),
                "kind": "element",
                "name": distribution,
                "tag_name": tag_name,
            },
            indent=2,
        )
    )
    return 0
