"""Edron: a class-oriented authoring facade for Hedron."""

__version__ = "0.9.1"

from edron.app import App
from edron.browser import (
    HEDRON_BROWSER_FORWARD_TARGET,
    HEDRON_BROWSER_REQUIREMENT,
    HEDRON_BROWSER_TRAIN,
    AlpineAttrs,
    AlpineDirective,
    AlpineExpression,
    AlpineFeatureDemand,
    AlpineMaturity,
    BrowserFeaturePlan,
    BrowserPlanClosure,
    browser_closure,
    browser_plan,
    feature_demand,
)
from edron.cache import CachedFunction, cache_data
from edron.capabilities import (
    BrokenCapabilityError,
    CapabilityError,
    IncompatibleCapabilityError,
    MissingCapabilityError,
)
from edron.composition import FeaturePackage, PackageConflictError, feature_package
from edron.confirm import Confirm
from edron.data import (
    AuditEvent,
    CellEdit,
    Column,
    DataExport,
    DataSelection,
    DataSource,
    DataWorkspace,
    EditIntent,
    EditPolicy,
    PageRequest,
    WorkspacePage,
)
from edron.dependencies import Dependency, Resource, dependency, resource
from edron.deployment import (
    ARTIFACT_SCHEMA,
    PROFILE_NAMES,
    PROFILE_SCHEMA,
    BackendMode,
    DeploymentError,
    DeploymentProfile,
    DeploymentProfileName,
    DeploymentReport,
    DeploymentResolution,
    artifact_manifest,
    artifact_records,
    check_deployment,
    deployment_report,
    profile_from_environment,
    resolve_deployment_profile,
)
from edron.deprecations import DEPRECATED_HEDRON_067_PATHS, deprecated_hedron_paths
from edron.descriptors import (
    Action,
    BoundAction,
    BoundFragment,
    Fragment,
    action,
    expose,
    fragment,
    inherit,
)
from edron.diagnostics import DiagnosticReport, EdronDiagnostic, SourceLocation
from edron.downloads import Download, download
from edron.errors import BindingError, EdronError, PhaseError, RegistrationError
from edron.interaction import Interaction, InteractionKind, Outcome, OutcomeKind
from edron.jobs import (  # pyright: ignore[reportUnknownVariableType]
    JobBackend,
    JobFlow,
    JobScope,
    job_status_events,
)
from edron.navigation import LAYOUT_KINDS, LayoutSpec, NavigationError, NavigationTarget, layout
from edron.outcomes import refresh, success
from edron.page import Container, FilterScope, Page
from edron.promotion import CapabilityPromotion, promoted_capabilities, promoted_capability
from edron.scaffolds import TEMPLATES, create_scaffold
from edron.styling import Color, DesignSystem, StyleContext, StyleRecipe, Theme, ThemeSpec, theme

__all__ = [
    "Action",
    "App",
    "AlpineAttrs",
    "AlpineDirective",
    "AlpineExpression",
    "AlpineFeatureDemand",
    "AlpineMaturity",
    "ARTIFACT_SCHEMA",
    "BackendMode",
    "BindingError",
    "BoundAction",
    "BoundFragment",
    "BrowserFeaturePlan",
    "BrowserPlanClosure",
    "CachedFunction",
    "CapabilityError",
    "CapabilityPromotion",
    "Color",
    "Column",
    "Confirm",
    "Container",
    "Dependency",
    "DeploymentError",
    "DeploymentProfile",
    "DeploymentProfileName",
    "DeploymentReport",
    "DeploymentResolution",
    "Resource",
    "DataExport",
    "DataSelection",
    "DataSource",
    "DataWorkspace",
    "DEPRECATED_HEDRON_067_PATHS",
    "DiagnosticReport",
    "DesignSystem",
    "Download",
    "EdronError",
    "EdronDiagnostic",
    "EditIntent",
    "EditPolicy",
    "FilterScope",
    "FeaturePackage",
    "Fragment",
    "IncompatibleCapabilityError",
    "JobBackend",
    "JobFlow",
    "JobScope",
    "job_status_events",
    "MissingCapabilityError",
    "BrokenCapabilityError",
    "Interaction",
    "InteractionKind",
    "Outcome",
    "OutcomeKind",
    "PackageConflictError",
    "Page",
    "PROFILE_NAMES",
    "PROFILE_SCHEMA",
    "PageRequest",
    "LayoutSpec",
    "NavigationError",
    "NavigationTarget",
    "LAYOUT_KINDS",
    "PhaseError",
    "RegistrationError",
    "StyleContext",
    "StyleRecipe",
    "Theme",
    "ThemeSpec",
    "TEMPLATES",
    "action",
    "artifact_manifest",
    "artifact_records",
    "check_deployment",
    "cache_data",
    "create_scaffold",
    "dependency",
    "deployment_report",
    "deprecated_hedron_paths",
    "resource",
    "browser_closure",
    "browser_plan",
    "feature_demand",
    "HEDRON_BROWSER_FORWARD_TARGET",
    "HEDRON_BROWSER_REQUIREMENT",
    "HEDRON_BROWSER_TRAIN",
    "profile_from_environment",
    "resolve_deployment_profile",
    "download",
    "fragment",
    "inherit",
    "expose",
    "refresh",
    "success",
    "theme",
    "feature_package",
    "layout",
    "promoted_capability",
    "promoted_capabilities",
    "SourceLocation",
    "WorkspacePage",
    "AuditEvent",
    "CellEdit",
]
