"""hedron-core: framework-neutral typed rendering core."""

from __future__ import annotations

from hedron_core.addressable import AddressableDescriptor, addressable
from hedron_core.builtins import (
    Alert,
    Aside,
    Badge,
    Button,
    Card,
    Checkbox,
    CodeBlock,
    Container,
    DescriptionList,
    Divider,
    Footer,
    Form,
    FormErrors,
    FormField,
    Fragment,
    Grid,
    Head,
    Header,
    Heading,
    IconButton,
    Image,
    Inline,
    Label,
    Link,
    LinkButton,
    List,
    Main,
    Nav,
    Page,
    RadioGroup,
    Section,
    Select,
    Skeleton,
    Stack,
    SubmitButton,
    Table,
    Text,
    TextArea,
    TextInput,
    Title,
)
from hedron_core.component import Component, ComponentNode, NodeLike
from hedron_core.diagnostics import Diagnostic, DiagnosticSeverity, HedronError
from hedron_core.field import Field
from hedron_core.html import html
from hedron_core.models import EventPayload, FormModel, Model, Props
from hedron_core.registry import (
    AddressableMeta,
    RouteMeta,
    get_registry,
    register_addressable,
    register_component,
    register_route,
    reset_registry_for_tests,
    seal_registry,
)
from hedron_core.rendering import AssetRef, RenderContext, RenderMode, RenderResult, render
from hedron_core.security import SafeUrl, Secret, TrustedHtml, UrlPurpose

__version__ = "0.2.0"

__all__ = [
    "AddressableDescriptor",
    "AddressableMeta",
    "Alert",
    "Aside",
    "AssetRef",
    "Badge",
    "Button",
    "Card",
    "Checkbox",
    "CodeBlock",
    "Component",
    "ComponentNode",
    "Container",
    "DescriptionList",
    "Diagnostic",
    "DiagnosticSeverity",
    "Divider",
    "EventPayload",
    "Field",
    "Footer",
    "Form",
    "FormErrors",
    "FormField",
    "FormModel",
    "Fragment",
    "Grid",
    "Head",
    "Header",
    "Heading",
    "HedronError",
    "IconButton",
    "Image",
    "Inline",
    "Label",
    "Link",
    "LinkButton",
    "List",
    "Main",
    "Model",
    "Nav",
    "NodeLike",
    "Page",
    "Props",
    "RadioGroup",
    "RenderContext",
    "RenderMode",
    "RenderResult",
    "RouteMeta",
    "SafeUrl",
    "Secret",
    "Section",
    "Select",
    "Skeleton",
    "Stack",
    "SubmitButton",
    "Table",
    "Text",
    "TextArea",
    "TextInput",
    "Title",
    "TrustedHtml",
    "UrlPurpose",
    "__version__",
    "addressable",
    "get_registry",
    "html",
    "register_addressable",
    "register_component",
    "register_route",
    "render",
    "reset_registry_for_tests",
    "seal_registry",
]


def _register_builtins() -> None:
    for cls in (
        Page,
        Fragment,
        Head,
        Title,
        Header,
        Main,
        Nav,
        Aside,
        Footer,
        Section,
        Container,
        Stack,
        Inline,
        Grid,
        Divider,
        Heading,
        Text,
        Link,
        Image,
        CodeBlock,
        List,
        DescriptionList,
        Table,
        Card,
        Badge,
        Alert,
        Skeleton,
        Button,
        LinkButton,
        IconButton,
        Form,
        FormField,
        Label,
        TextInput,
        TextArea,
        Select,
        Checkbox,
        RadioGroup,
        SubmitButton,
        FormErrors,
    ):
        logical = (
            f"{getattr(cls, 'distribution', 'hedron-core')}:"
            f"{cls.__module__}.{getattr(cls, 'logical_name', cls.__name__)}"
        )
        register_component(
            logical_id=logical,
            name=getattr(cls, "logical_name", cls.__name__) or cls.__name__,
            module=cls.__module__,
            distribution=getattr(cls, "distribution", "hedron-core"),
            props_model=getattr(cls, "props_type", type(None)).__name__,
            slots=getattr(cls, "slots", {}),
            accessibility_notes="Uses native semantic HTML without JavaScript.",
        )
    # Do not seal on import — applications seal at lifespan; tests may register more.


_register_builtins()
