"""hedron-core: framework-neutral typed rendering core."""

from __future__ import annotations

from hedron_core.adapter import (
    AuthSignal,
    CapabilityRecord,
    LifecycleResource,
    UrlReverseRequest,
    capability_matrix,
)
from hedron_core.addressable import AddressableDescriptor, addressable
from hedron_core.auto import Auto, inspect_data, register_renderer
from hedron_core.builtins import (
    Alert,
    Aside,
    Badge,
    Button,
    Card,
    Checkbox,
    CodeBlock,
    CodeViewer,
    Container,
    DescriptionList,
    Divider,
    Expander,
    Footer,
    Form,
    FormErrors,
    FormField,
    Fragment,
    Grid,
    Head,
    Header,
    Heading,
    IconButton,
    Image,
    Inline,
    JSONViewer,
    Label,
    Link,
    LinkButton,
    List,
    Main,
    Metric,
    Nav,
    Page,
    Progress,
    RadioGroup,
    Section,
    Select,
    Sidebar,
    Skeleton,
    Stack,
    Status,
    SubmitButton,
    Table,
    Tabs,
    Text,
    TextArea,
    TextInput,
    Title,
    Toast,
)
from hedron_core.cache import (
    CacheScope,
    CacheTrace,
    InMemoryCacheBackend,
    get_cache_traces,
    invalidate_tags,
    reset_cache_for_tests,
)
from hedron_core.color_mode import ColorMode, ColorModeToggle, color_mode_script, resolve_color_mode
from hedron_core.component import Component, ComponentNode, NodeLike
from hedron_core.css import compile_css, scoped_identifier
from hedron_core.diagnostics import (
    Diagnostic,
    DiagnosticSeverity,
    HedronError,
    SourceSpan,
    Suppression,
    apply_suppressions,
    diagnostics_to_json,
    diagnostics_to_sarif,
    diagnostics_to_text,
    meets_severity_threshold,
)
from hedron_core.field import Field
from hedron_core.html import html
from hedron_core.htmx_contract import HtmxContext, approved_headers
from hedron_core.icons import IconEntry, get_icon, list_icons, register_icon, trusted_svg
from hedron_core.interaction import (
    FragmentRegion,
    InteractionPolicy,
    InteractionResult,
    OobUpdate,
    StatusPolicy,
    default_interaction_policy,
    interaction_headers,
)
from hedron_core.models import EventPayload, FormModel, Model, Props
from hedron_core.registry import (
    AddressableMeta,
    RouteMeta,
    get_registry,
    register_addressable,
    register_browser_module,
    register_component,
    register_route,
    register_theme,
    reset_registry_for_tests,
    seal_registry,
)
from hedron_core.rendering import AssetRef, RenderContext, RenderMode, RenderResult, render
from hedron_core.security import SafeUrl, Secret, TrustedHtml, UrlPurpose
from hedron_core.styles import StyleSymbols, styles_from_manifest
from hedron_core.theme import Theme, default_theme, emit_theme_css
from hedron_core.visualization import (
    ChartAccessibility,
    ChartOutput,
    VisualizationAdapter,
    VisualizationLimits,
)

__version__ = "0.9.0"

__all__ = [
    "AddressableDescriptor",
    "AddressableMeta",
    "Alert",
    "AuthSignal",
    "CapabilityRecord",
    "FragmentRegion",
    "HtmxContext",
    "InteractionPolicy",
    "InteractionResult",
    "LifecycleResource",
    "OobUpdate",
    "StatusPolicy",
    "UrlReverseRequest",
    "approved_headers",
    "capability_matrix",
    "default_interaction_policy",
    "interaction_headers",
    "Aside",
    "AssetRef",
    "Badge",
    "Button",
    "Card",
    "Checkbox",
    "CodeBlock",
    "Component",
    "ComponentNode",
    "Container",
    "DescriptionList",
    "Diagnostic",
    "DiagnosticSeverity",
    "Divider",
    "EventPayload",
    "Field",
    "Footer",
    "Form",
    "FormErrors",
    "FormField",
    "FormModel",
    "Fragment",
    "Grid",
    "Head",
    "Header",
    "Heading",
    "HedronError",
    "IconButton",
    "Image",
    "Inline",
    "Label",
    "Link",
    "LinkButton",
    "List",
    "Main",
    "Model",
    "Nav",
    "NodeLike",
    "Page",
    "Props",
    "RadioGroup",
    "RenderContext",
    "RenderMode",
    "RenderResult",
    "RouteMeta",
    "SafeUrl",
    "Secret",
    "Section",
    "Select",
    "Skeleton",
    "Stack",
    "SourceSpan",
    "StyleSymbols",
    "SubmitButton",
    "Suppression",
    "Table",
    "Text",
    "TextArea",
    "TextInput",
    "Theme",
    "Title",
    "TrustedHtml",
    "UrlPurpose",
    "Auto",
    "CacheScope",
    "CacheTrace",
    "ChartAccessibility",
    "ChartOutput",
    "CodeViewer",
    "ColorMode",
    "ColorModeToggle",
    "color_mode_script",
    "Expander",
    "IconEntry",
    "InMemoryCacheBackend",
    "JSONViewer",
    "Metric",
    "Progress",
    "Sidebar",
    "Status",
    "Tabs",
    "Toast",
    "VisualizationAdapter",
    "VisualizationLimits",
    "get_cache_traces",
    "get_icon",
    "inspect_data",
    "invalidate_tags",
    "list_icons",
    "register_icon",
    "register_renderer",
    "reset_cache_for_tests",
    "resolve_color_mode",
    "trusted_svg",
    "__version__",
    "addressable",
    "apply_suppressions",
    "compile_css",
    "default_theme",
    "diagnostics_to_json",
    "diagnostics_to_sarif",
    "diagnostics_to_text",
    "emit_theme_css",
    "get_registry",
    "html",
    "meets_severity_threshold",
    "register_addressable",
    "register_browser_module",
    "register_component",
    "register_route",
    "register_theme",
    "render",
    "reset_registry_for_tests",
    "scoped_identifier",
    "seal_registry",
    "styles_from_manifest",
]


def _register_builtins() -> None:
    for cls in (
        Page,
        Fragment,
        Head,
        Title,
        Header,
        Main,
        Nav,
        Aside,
        Footer,
        Section,
        Container,
        Stack,
        Inline,
        Grid,
        Divider,
        Heading,
        Text,
        Link,
        Image,
        CodeBlock,
        List,
        DescriptionList,
        Table,
        Metric,
        CodeViewer,
        JSONViewer,
        Progress,
        Status,
        Toast,
        Expander,
        Tabs,
        Sidebar,
        ColorModeToggle,
        Auto,
        Card,
        Badge,
        Alert,
        Skeleton,
        Button,
        LinkButton,
        IconButton,
        Form,
        FormField,
        Label,
        TextInput,
        TextArea,
        Select,
        Checkbox,
        RadioGroup,
        SubmitButton,
        FormErrors,
    ):
        logical = (
            f"{getattr(cls, 'distribution', 'hedron-core')}:"
            f"{cls.__module__}.{getattr(cls, 'logical_name', cls.__name__)}"
        )
        register_component(
            logical_id=logical,
            name=getattr(cls, "logical_name", cls.__name__) or cls.__name__,
            module=cls.__module__,
            distribution=getattr(cls, "distribution", "hedron-core"),
            props_model=getattr(cls, "props_type", type(None)).__name__,
            slots=getattr(cls, "slots", {}),
            accessibility_notes="Uses native semantic HTML without JavaScript.",
        )


_register_builtins()
