"""HTML tag and attribute metadata for the serializer."""

from __future__ import annotations

VOID_TAGS = frozenset(
    {
        "area",
        "base",
        "br",
        "col",
        "embed",
        "hr",
        "img",
        "input",
        "link",
        "meta",
        "param",
        "source",
        "track",
        "wbr",
    }
)

# Common HTML elements accepted by html.* and built-ins.
KNOWN_TAGS = frozenset(
    {
        "a",
        "abbr",
        "address",
        "article",
        "aside",
        "audio",
        "b",
        "blockquote",
        "body",
        "br",
        "button",
        "canvas",
        "caption",
        "cite",
        "code",
        "col",
        "colgroup",
        "data",
        "datalist",
        "dd",
        "del",
        "details",
        "dfn",
        "dialog",
        "div",
        "dl",
        "dt",
        "em",
        "embed",
        "fieldset",
        "figcaption",
        "figure",
        "footer",
        "form",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "head",
        "header",
        "hgroup",
        "hr",
        "html",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "legend",
        "li",
        "link",
        "main",
        "map",
        "mark",
        "menu",
        "meta",
        "meter",
        "nav",
        "noscript",
        "object",
        "ol",
        "optgroup",
        "option",
        "output",
        "p",
        "picture",
        "pre",
        "progress",
        "q",
        "rp",
        "rt",
        "ruby",
        "s",
        "samp",
        "script",
        "search",
        "section",
        "select",
        "slot",
        "small",
        "source",
        "span",
        "strong",
        "style",
        "sub",
        "summary",
        "sup",
        "table",
        "tbody",
        "td",
        "template",
        "textarea",
        "tfoot",
        "th",
        "thead",
        "time",
        "title",
        "tr",
        "track",
        "u",
        "ul",
        "var",
        "video",
        "wbr",
    }
)

BOOLEAN_ATTRS = frozenset(
    {
        "allowfullscreen",
        "async",
        "autofocus",
        "autoplay",
        "checked",
        "controls",
        "default",
        "defer",
        "disabled",
        "formnovalidate",
        "hidden",
        "inert",
        "ismap",
        "itemscope",
        "loop",
        "multiple",
        "muted",
        "nomodule",
        "novalidate",
        "open",
        "readonly",
        "required",
        "reversed",
        "selected",
    }
)

URL_ATTRS = frozenset(
    {
        "action",
        "cite",
        "data",
        "formaction",
        "href",
        "poster",
        "src",
        "xlink:href",
    }
)

ATTR_ALIASES = {
    "class_": "class",
    "for_": "for",
    "as_": "as",
    "type_": "type",
    "id_": "id",
}

# Deterministic preferred attribute order (others follow alphabetically).
ATTR_ORDER = (
    "id",
    "class",
    "type",
    "name",
    "href",
    "src",
    "alt",
    "title",
    "role",
    "for",
    "value",
    "placeholder",
    "disabled",
    "readonly",
    "required",
    "checked",
    "selected",
    "hidden",
    "method",
    "action",
    "rel",
    "target",
    "download",
    "width",
    "height",
    "colspan",
    "rowspan",
    "scope",
    "tabindex",
)
