"""Stable diagnostic code catalog for phase 0.3 areas."""

from __future__ import annotations

# Config
HED_CONFIG_UNKNOWN_KEY = "HED-CONFIG-0001"
HED_CONFIG_UNSUPPORTED_VERSION = "HED-CONFIG-0002"
HED_CONFIG_INVALID = "HED-CONFIG-0003"

# Build
HED_BUILD_UNSUPPORTED_VERSION = "HED-BUILD-0001"
HED_BUILD_FAILED = "HED-BUILD-0002"
HED_BUILD_MISSING_MANIFEST = "HED-BUILD-0003"
HED_BUILD_RUNTIME_COMPILE = "HED-BUILD-0004"

# Assets
HED_ASSET_UNSUPPORTED_VERSION = "HED-ASSET-0001"
HED_ASSET_TRAVERSAL = "HED-ASSET-0002"
HED_ASSET_REMOTE = "HED-ASSET-0003"
HED_ASSET_MISSING = "HED-ASSET-0004"
HED_ASSET_COLLISION = "HED-ASSET-0005"
HED_ASSET_SYMLINK = "HED-ASSET-0006"
HED_ASSET_MIME = "HED-ASSET-0007"

# CSS
HED_CSS_UNSUPPORTED_VERSION = "HED-CSS-0001"
HED_CSS_PARSE = "HED-CSS-0002"
HED_CSS_UNKNOWN_SYMBOL = "HED-CSS-0003"
HED_CSS_UNSAFE_GLOBAL = "HED-CSS-0004"
HED_CSS_REMOTE = "HED-CSS-0005"
HED_CSS_INLINE = "HED-CSS-0006"
HED_CSS_DUPLICATE = "HED-CSS-0007"
HED_CSS_UNUSED = "HED-CSS-0008"

# Themes
HED_THEME_UNKNOWN = "HED-THEME-0001"
HED_THEME_MISSING_TOKEN = "HED-THEME-0002"
HED_THEME_INVALID = "HED-THEME-0003"
HED_THEME_DUPLICATE = "HED-THEME-0004"

# HDN
HED_HDN_PARSE = "HED-HDN-0001"
HED_HDN_LEX = "HED-HDN-0002"
HED_HDN_TYPE = "HED-HDN-0003"
HED_HDN_UNKNOWN_COMPONENT = "HED-HDN-0004"
HED_HDN_UNSAFE = "HED-HDN-0005"
HED_HDN_TRUSTED = "HED-HDN-0006"
HED_HDN_UNKNOWN_HELPER = "HED-HDN-0007"
HED_HDN_FORMAT = "HED-HDN-0008"
HED_HDN_SLOT = "HED-HDN-0009"

# Web Components / browser
HED_BROWSER_DUPLICATE = "HED-ASSET-0010"
HED_BROWSER_INVALID = "HED-ASSET-0011"

# Plugins
HED_PLUGIN_MISSING = "HED-PLUGIN-0001"
HED_PLUGIN_INCOMPATIBLE = "HED-PLUGIN-0002"
HED_PLUGIN_CYCLE = "HED-PLUGIN-0003"
HED_PLUGIN_DUPLICATE = "HED-PLUGIN-0004"
HED_PLUGIN_FAILED = "HED-PLUGIN-0005"
