"""Closed inert JSON Schema sanitizer for TypeSchema v2 projections."""

from __future__ import annotations

from collections.abc import Mapping, MutableMapping
from typing import Any, NoReturn, cast

from hedron_core.codes import HED_FP_0003
from hedron_core.diagnostics import error
from hedron_core.security.urls import nfkc_strip_format
from hedron_core.type_schema import MAX_SCHEMA_DEPTH, redact_type_payload
from hedron_core.typing_aliases import JsonObject, JsonValue

__all__ = [
    "ALLOWED_SCHEMA_KEYWORDS",
    "FORBIDDEN_SCHEMA_KEYWORDS",
    "sanitize_json_schema",
]

FORBIDDEN_SCHEMA_KEYWORDS = frozenset(
    {
        "values",
        "defaults",
        "examples",
        "example",
        "default",
        "callbacks",
        "request",
        "model",
        "contentEncoding",
        "$dynamicAnchor",
        "$dynamicRef",
    }
)
ALLOWED_SCHEMA_KEYWORDS = frozenset(
    {
        "$schema",
        "$id",
        "$ref",
        "$anchor",
        "$comment",
        "$defs",
        "definitions",
        "type",
        "properties",
        "patternProperties",
        "additionalProperties",
        "unevaluatedProperties",
        "required",
        "dependentRequired",
        "dependentSchemas",
        "propertyNames",
        "items",
        "prefixItems",
        "additionalItems",
        "unevaluatedItems",
        "contains",
        "minContains",
        "maxContains",
        "minItems",
        "maxItems",
        "uniqueItems",
        "minProperties",
        "maxProperties",
        "enum",
        "const",
        "multipleOf",
        "maximum",
        "exclusiveMaximum",
        "minimum",
        "exclusiveMinimum",
        "maxLength",
        "minLength",
        "pattern",
        "format",
        "anyOf",
        "oneOf",
        "allOf",
        "not",
        "if",
        "then",
        "else",
        "title",
        "description",
        "deprecated",
        "readOnly",
        "writeOnly",
        "contentMediaType",
        "contentSchema",
        "nullable",
        "discriminator",
    }
)
_SCHEMA_MAP_CHILDREN = frozenset(
    {
        "additionalProperties",
        "unevaluatedProperties",
        "items",
        "not",
        "if",
        "then",
        "else",
        "propertyNames",
        "unevaluatedItems",
        "contains",
        "contentSchema",
        "discriminator",
    }
)
_SCHEMA_NAMED_MAP_CHILDREN = frozenset(
    {
        "properties",
        "$defs",
        "definitions",
        "patternProperties",
        "dependentSchemas",
    }
)
_SCHEMA_ARRAY_CHILDREN = frozenset({"anyOf", "oneOf", "allOf", "prefixItems"})


def _keyword(name: str) -> str:
    return nfkc_strip_format(str(name))


def _refuse(title: str, explanation: str, *, remediation: str) -> NoReturn:
    raise error(
        HED_FP_0003,
        title=title,
        explanation=explanation,
        remediation=remediation,
    )


def _copy_json(value: Any, *, keyword: str) -> JsonValue:
    if callable(value):
        _refuse(
            "Executable JSON Schema hook refused",
            f"Keyword {keyword!r} carried a callable.",
            remediation="Use inert JSON Schema generated by Pydantic, then sanitized.",
        )
    if isinstance(value, Mapping):
        return {str(key): _copy_json(item, keyword=keyword) for key, item in value.items()}
    if isinstance(value, list):
        return [_copy_json(item, keyword=keyword) for item in value]
    return cast(JsonValue, value)


def _sanitize_named_schemas(value: Mapping[str, Any], *, depth: int) -> JsonObject:
    out: dict[str, JsonValue] = {}
    for key, item in value.items():
        if isinstance(item, Mapping):
            out[str(key)] = sanitize_json_schema(cast(Mapping[str, Any], item), depth=depth)
        elif callable(item):
            _refuse(
                "Executable JSON Schema hook refused",
                f"Nested schema {str(key)!r} carried a callable.",
                remediation="Use inert JSON Schema generated by Pydantic, then sanitized.",
            )
        else:
            out[str(key)] = cast(JsonValue, item)
    return out


def sanitize_json_schema(schema: Mapping[str, Any] | None, *, depth: int = 0) -> JsonObject:
    """Drop secrets/defaults/examples and fail closed on unknown recursion/executables."""
    if schema is None:
        return {}
    if depth > MAX_SCHEMA_DEPTH:
        _refuse(
            "JSON Schema depth exceeded",
            f"Projection exceeded TypeSchema depth {MAX_SCHEMA_DEPTH}.",
            remediation="Flatten the model or fail closed at the boundary.",
        )
    out: dict[str, JsonValue] = {}
    for key, value in schema.items():
        name = _keyword(str(key))
        if name in FORBIDDEN_SCHEMA_KEYWORDS:
            continue
        if name not in ALLOWED_SCHEMA_KEYWORDS:
            _refuse(
                "Unknown JSON Schema keyword refused",
                f"Keyword {name!r} is not in the TypeSchema v2 allowlist.",
                remediation="Use inert Pydantic JSON Schema without extra keywords or secrets.",
            )
        if callable(value):
            _refuse(
                "Executable JSON Schema hook refused",
                f"Keyword {name!r} carried a callable.",
                remediation="Use inert JSON Schema generated by Pydantic, then sanitized.",
            )
        if name in {"$ref", "$defs", "definitions"} and depth > 8:
            _refuse(
                "Unsupported schema recursion",
                "Deep $ref graphs are not projected.",
                remediation="Simplify the boundary model.",
            )
        if name in _SCHEMA_NAMED_MAP_CHILDREN and isinstance(value, Mapping):
            out[name] = _sanitize_named_schemas(cast(Mapping[str, Any], value), depth=depth + 1)
        elif name in _SCHEMA_MAP_CHILDREN and isinstance(value, Mapping):
            out[name] = sanitize_json_schema(cast(Mapping[str, Any], value), depth=depth + 1)
        elif name in _SCHEMA_ARRAY_CHILDREN and isinstance(value, list):
            cleaned: list[JsonValue] = []
            for item in value:
                if isinstance(item, Mapping):
                    cleaned.append(
                        sanitize_json_schema(cast(Mapping[str, Any], item), depth=depth + 1)
                    )
                elif callable(item):
                    _refuse(
                        "Executable JSON Schema hook refused",
                        f"Keyword {name!r} listed a callable.",
                        remediation="Remove custom schema callables.",
                    )
                else:
                    cleaned.append(cast(JsonValue, item))
            out[name] = cleaned
        else:
            out[name] = _copy_json(value, keyword=name)
    return redact_type_payload(cast(MutableMapping[str, JsonValue], out))


def projections_from_model(
    model_type: type[Any] | None,
    *,
    sensitive: tuple[str, ...] = (),
    identity: tuple[str, ...] = (),
    computed: tuple[str, ...] = (),
) -> tuple[JsonObject, JsonObject, tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """Return sanitized input/output projections and field classifications."""
    del identity
    if model_type is None:
        return {}, {}, (), (), ()
    schema_fn = getattr(model_type, "model_json_schema", None)
    if not callable(schema_fn):
        return {}, {}, (), sensitive, computed
    raw = schema_fn()
    if not isinstance(raw, Mapping):
        return {}, {}, (), sensitive, computed
    sanitized = sanitize_json_schema(cast(Mapping[str, Any], raw))
    properties = sanitized.get("properties")
    names: tuple[str, ...] = ()
    if isinstance(properties, dict):
        names = tuple(str(key) for key in properties)
    write_only = tuple(item for item in sensitive if item in names or not names)
    read_only = tuple(item for item in computed)
    shared = tuple(item for item in names if item not in write_only and item not in read_only)
    input_proj = dict(sanitized)
    output_proj = dict(sanitized)
    if isinstance(properties, dict) and write_only:
        out_props = {key: value for key, value in properties.items() if key not in write_only}
        output_proj = {**sanitized, "properties": out_props}
    if isinstance(properties, dict) and read_only:
        in_props = {key: value for key, value in properties.items() if key not in read_only}
        input_proj = {**sanitized, "properties": in_props}
    return input_proj, output_proj, shared, write_only, read_only
