"""Closed inert JSON Schema sanitizer for TypeSchema v2 projections."""

from __future__ import annotations

from collections.abc import Mapping, MutableMapping
from typing import Any, cast

from hedron_core.codes import HED_FP_0003
from hedron_core.diagnostics import error
from hedron_core.type_schema import MAX_SCHEMA_DEPTH, redact_type_payload
from hedron_core.typing_aliases import JsonObject, JsonValue

__all__ = [
    "FORBIDDEN_SCHEMA_KEYWORDS",
    "sanitize_json_schema",
]

FORBIDDEN_SCHEMA_KEYWORDS = frozenset(
    {
        "values",
        "defaults",
        "examples",
        "example",
        "default",
        "callbacks",
        "request",
        "model",
        "contentEncoding",
        "$dynamicAnchor",
        "$dynamicRef",
    }
)
_EXECUTABLE_KEYWORDS = frozenset()  # callables fail closed; format stays a string constraint


def sanitize_json_schema(schema: Mapping[str, Any] | None, *, depth: int = 0) -> JsonObject:
    """Drop secrets/defaults/examples and fail closed on unknown recursion/executables."""
    if schema is None:
        return {}
    if depth > MAX_SCHEMA_DEPTH:
        raise error(
            HED_FP_0003,
            title="JSON Schema depth exceeded",
            explanation=f"Projection exceeded TypeSchema depth {MAX_SCHEMA_DEPTH}.",
            remediation="Flatten the model or fail closed at the boundary.",
        )
    out: dict[str, JsonValue] = {}
    for key, value in schema.items():
        name = str(key)
        if name in FORBIDDEN_SCHEMA_KEYWORDS or name.startswith("x-"):
            continue
        if callable(value):
            raise error(
                HED_FP_0003,
                title="Executable JSON Schema hook refused",
                explanation=f"Keyword {name!r} carried a callable.",
                remediation="Use inert JSON Schema generated by Pydantic, then sanitized.",
            )
        if name in {"$ref", "$defs", "definitions"} and depth > 8:
            raise error(
                HED_FP_0003,
                title="Unsupported schema recursion",
                explanation="Deep $ref graphs are not projected.",
                remediation="Simplify the boundary model.",
            )
        if isinstance(value, Mapping):
            out[name] = sanitize_json_schema(cast(Mapping[str, Any], value), depth=depth + 1)
        elif isinstance(value, list):
            cleaned: list[JsonValue] = []
            for item in value:
                if isinstance(item, Mapping):
                    cleaned.append(
                        sanitize_json_schema(cast(Mapping[str, Any], item), depth=depth + 1)
                    )
                elif callable(item):
                    raise error(
                        HED_FP_0003,
                        title="Executable JSON Schema hook refused",
                        explanation=f"Keyword {name!r} listed a callable.",
                        remediation="Remove custom schema callables.",
                    )
                else:
                    cleaned.append(cast(JsonValue, item))
            out[name] = cleaned
        else:
            out[name] = cast(JsonValue, value)
    return redact_type_payload(cast(MutableMapping[str, JsonValue], out))


def projections_from_model(
    model_type: type[Any] | None,
    *,
    sensitive: tuple[str, ...] = (),
    identity: tuple[str, ...] = (),
    computed: tuple[str, ...] = (),
) -> tuple[JsonObject, JsonObject, tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """Return sanitized input/output projections and field classifications."""
    del identity
    if model_type is None:
        return {}, {}, (), (), ()
    schema_fn = getattr(model_type, "model_json_schema", None)
    if not callable(schema_fn):
        return {}, {}, (), sensitive, computed
    raw = schema_fn()
    if not isinstance(raw, Mapping):
        return {}, {}, (), sensitive, computed
    sanitized = sanitize_json_schema(cast(Mapping[str, Any], raw))
    properties = sanitized.get("properties")
    names: tuple[str, ...] = ()
    if isinstance(properties, dict):
        names = tuple(str(key) for key in properties)
    write_only = tuple(item for item in sensitive if item in names or not names)
    read_only = tuple(item for item in computed)
    shared = tuple(item for item in names if item not in write_only and item not in read_only)
    input_proj = dict(sanitized)
    output_proj = dict(sanitized)
    if isinstance(properties, dict) and write_only:
        out_props = {key: value for key, value in properties.items() if key not in write_only}
        output_proj = {**sanitized, "properties": out_props}
    if isinstance(properties, dict) and read_only:
        in_props = {key: value for key, value in properties.items() if key not in read_only}
        input_proj = {**sanitized, "properties": in_props}
    return input_proj, output_proj, shared, write_only, read_only
